### PR TITLE
March Tape Test configuration

### PR DESCRIPTION
**Pull request by germanfgv**
Replay configuration for March Tape Test.

### CODE REVIEW

**Comment by jhonatanamado** [comment]
Hi German, Just a single comment, this line https://github.com/dmwm/T0/blob/45f349e49ed1c64ae911bfee679183c080489d85/etc/ReplayOfflineConfiguration.py#L221 will not create also container subscriptions at T0_CH_CERN_Disk? Are those additional subscriptions desired?

**Comment by jhonatanamado** [comment]
Hi @germanfgv, The following are the additional subscriptions created at T0_CH_CERN_Disk due the following line https://github.com/dmwm/T0/blob/45f349e49ed1c64ae911bfee679183c080489d85/etc/ReplayOfflineConfiguration.py#L221 
```
4816b0e30e214c028906d00c411e4a56 T0_CH_CERN_Disk CONTAINER /D15/MarchTapeTest2022-v4/RAW
a30a31c53b564e8bb5c5f52c96800f64 T0_CH_CERN_Disk CONTAINER /D18/MarchTapeTest2022-v4/RAW
c4fa49b5e0c1484e8c52daa8442edf7b T0_CH_CERN_Disk CONTAINER /D09/MarchTapeTest2022-v4/RAW
e55e7e9e12c14fc498b659c3fa172c3d T0_CH_CERN_Disk CONTAINER /D05/MarchTapeTest2022-v4/RAW
3345fe91d4a245e1bd97d01a6432333a T0_CH_CERN_Disk CONTAINER /D10/MarchTapeTest2022-v4/RAW
481564d08e194debb26be75d9c3086a6 T0_CH_CERN_Disk CONTAINER /D25/MarchTapeTest2022-v4/RAW
bfae44ef5bca4a1b8283d1ca5263356c T0_CH_CERN_Disk CONTAINER /D23/MarchTapeTest2022-v4/RAW
0953b579d99c4635911e923f8bb3d027 T0_CH_CERN_Disk CONTAINER /D24/MarchTapeTest2022-v4/RAW
de66c2ba20b344969698d6afbd322525 T0_CH_CERN_Disk CONTAINER /D03/MarchTapeTest2022-v4/RAW
f5ebb04587a64712abade428b23a4c68 T0_CH_CERN_Disk CONTAINER /D20/MarchTapeTest2022-v4/RAW
460338ded41940fda2a953705bb5d7b6 T0_CH_CERN_Disk CONTAINER /D19/MarchTapeTest2022-v4/RAW
e5d1dcfb3e754b0fafea553efc12bf13 T0_CH_CERN_Disk CONTAINER /D07/MarchTapeTest2022-v4/RAW
ab3b894a3ecc48b7834e74eb7a899a25 T0_CH_CERN_Disk CONTAINER /D22/MarchTapeTest2022-v4/RAW
be6a56cb0632495ea105af6e33633ef4 T0_CH_CERN_Disk CONTAINER /D04/MarchTapeTest2022-v4/RAW
38730da60a1f40d7bfd86dcbbf7ea37b T0_CH_CERN_Disk CONTAINER /D16/MarchTapeTest2022-v4/RAW
374cad566ecc494d88b3bf627df5e3bb T0_CH_CERN_Disk CONTAINER /D08/MarchTapeTest2022-v4/RAW
1fac330e38204461bb6115132cbe9919 T0_CH_CERN_Disk CONTAINER /D02/MarchTapeTest2022-v4/RAW
e6e1089a284c4b6489fcb841ce6c158f T0_CH_CERN_Disk CONTAINER /D12/MarchTapeTest2022-v4/RAW
d02f76d78de441ce92366be00a3d2684 T0_CH_CERN_Disk CONTAINER /D11/MarchTapeTest2022-v4/RAW
94e6cb5376b74b98a9d8430e228704bc T0_CH_CERN_Disk CONTAINER /D13/MarchTapeTest2022-v4/RAW
24e5cce378794381adb8069f4996494b T0_CH_CERN_Disk CONTAINER /D14/MarchTapeTest2022-v4/RAW
bbd43fe0933c44d9b7a70d6fbf2084c5 T0_CH_CERN_Disk CONTAINER /D17/MarchTapeTest2022-v4/RAW
457e6451b9624af5a86a6f9c46bd8942 T0_CH_CERN_Disk CONTAINER /D01/MarchTapeTest2022-v4/RAW
064a04b33cdb441baa5b1964a336a763 T0_CH_CERN_Disk CONTAINER /D21/MarchTapeTest2022-v4/RAW
42f2571d183a4935a543d90b344654ed T0_CH_CERN_Disk CONTAINER /D06/MarchTapeTest2022-v4/RAW
```
I deleted those rules because even if the workflow is archived and the block level rule deleted, the files will remain there due that container subscription protecting that data.

**Comment by drkovalskyi** [comment]
I would avoid manual interventions like that unless we are running out of space. We can just wait a few days for the tests to finish and clean up afterwords. Are we in danger of running out of space?

**Comment by germanfgv** [comment]
I'll close this PR as we dont want to have this config in masters

**Pull request closed without merging**
