### PR TITLE
11_3_4 Replay test

### PR DESCRIPTION
**Pull request by francescobrivio**
Test CMSSW_11_3_4 for CRUZET.

Runs include: 341169,341754,338628,338714,342154,343498,344063

Global Tags:
- expressGlobalTag = "113X_dataRun3_Express_v4"
- promptrecoGlobalTag = "113X_dataRun3_Prompt_v3"
- alcap0GlobalTag = "113X_dataRun3_Prompt_v3"

### CODE REVIEW

**Comment by francescobrivio** [comment]
FYI @germanfgv @perrotta

**Comment by francescobrivio** [comment]
@germanfgv I am part of the CMSTier0 group (https://github.com/orgs/CMSTier0/people) but apparently the permissions are still not working properly so I can not start the replay, and event the Syntax checks won't start...

**Comment by germanfgv** [comment]
run replay please

**Comment by germanfgv** [comment]
> @germanfgv I am part of the CMSTier0 group (https://github.com/orgs/CMSTier0/people) but apparently the permissions are still not working properly so I can not start the replay, and event the Syntax checks won't start...

@francescobrivio the problem is prabably that your membership to CMSTier0 is private, so Jenkins cannot verify if you belong to the group. I forgot to mention that to you in our previous chat. I you change that, you should be able to trigger the replays.

**Comment by francescobrivio** [comment]
> > @germanfgv I am part of the CMSTier0 group (https://github.com/orgs/CMSTier0/people) but apparently the permissions are still not working properly so I can not start the replay, and event the Syntax checks won't start...
> 
> @francescobrivio the problem is prabably that your membership to CMSTier0 is private, so Jenkins cannot verify if you belong to the group. I forgot to mention that to you in our previous chat. I you change that, you should be able to trigger the replays.

Thanks @germanfgv! I have changed it to "Public", I will test it at the next replay :)

**Comment by germanfgv** [comment]
@francescobrivio The replay has finished without any issues. I'll report it in HN.

**Comment by francescobrivio** [comment]
CMSSW_11_3_4 was succesfully deployed at P5 and used for data-taking.
This can be closed.

**Pull request closed without merging**
