### PR TITLE
Replay configuration for 13_0_1

### PR DESCRIPTION
**Pull request by mdmorris**
# Replay Request

**Requestor**  
ORM

**Describe the configuration**  
* Release: CMSSW_13_0_1
* Run: 364158,350966,359691
* GTs:
   * expressGlobalTag: 130X_dataRun3_Express_v1
   * promptrecoGlobalTag: 130X_dataRun3_Prompt_v1
* Additional changes:

**Purpose of the test**  
Testing for new release 13_0_1

### CODE REVIEW

**Comment by tvami** [comment]
hi @mdmorris 

can we please test 
```
expressGlobalTag: 130X_dataRun3_Express_v2
promptrecoGlobalTag: 130X_dataRun3_Prompt_v2
```
in this replay?

Thanks

**Comment by mdmorris** [comment]
hi @tvami, the global tags have been updated

**Comment by rappoccio** [comment]
run replay please

**Comment by germanfgv** [comment]
As mentioned in mattermost, I started this replay manually:

you can follow it here:
https://monit-grafana.cern.ch/d/t_jr45h7k/cms-tier0-replayid-monitoring?orgId=11&refresh=1m&var-Bin=5m&var-ReplayID=230329105933&var-JobType=All&var-WorkflowType=All

**Comment by germanfgv** [comment]
I'm changing the GT for `AlCaLumiPixelsCountsPrompt` to `130X_dataRun3_Prompt_Candidate_2023_03_09_09_47_16` as provided by @francescobrivio. 
This in order to avoid the error `No triggerList with key AlCaPCCRandom in AlCaRecoTriggerBitsRcd`

**Comment by germanfgv** [comment]
As discussed in previous meetings, this replay finished succesfully. I'll close the PR.

**Pull request closed without merging**
