### PR TITLE
Replay to validate new TkAlignment conditions [CRUZET2021] 

### PR DESCRIPTION
**Pull request by germanfgv**
Replay requested in [1] by @francescobrivio 

 [1] https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/2250.html

### CODE REVIEW

**Comment by germanfgv** [comment]
@francescobrivio Actually you should be able to request the start of the replay, as you have been added to the CMS Tier0 organization. All you have to do is comment the trigger phrase `run replay please`. Would you like to try it?

**Comment by francescobrivio** [comment]
> @francescobrivio Actually you should be able to request the start of the replay, as you have been added to the CMS Tier0 organization. All you have to do is comment the trigger phrase `run replay please`. Would you like to try it?

yes I'll try!

**Comment by francescobrivio** [comment]
run replay please

**Comment by germanfgv** [comment]
run replay please

**Comment by germanfgv** [comment]
> run replay please

Looks like there is still a problem with your permissions. I'll request the replay myself while I look into it.

**Comment by germanfgv** [comment]
@francescobrivio All processing jobs have finished and there were no issues.

**Pull request closed without merging**
