### PR TITLE
Changes for MWGR2 2016

### PR DESCRIPTION
**Pull request by johnhcasallasl**
+ New CMSSW version
+ New Architecture
+ Override of architecture for CMSSW_7_4_15
+ New scenarios (config and DB schema)
+ New GTs
+ @common dqm sequence 
+ Setting max latency in the default Repack config (only replays)

### CODE REVIEW

**Comment by johnhcasallasl** [comment]
- Override of architecture for CMSSW_7_5_8 added too

**Comment by johnhcasallasl** [comment]
Based on what Eliana proposed & David commented on HN:
- Architecture remains in 491
- CMSSW version in 8_0_0_patch1
- Override of architecture for CMSSW_8_0_0_patch1 to use 493. No more overrides needed. 
- Last year scenarios

**Comment by ebohorqu** [comment]
We are missing @common sequence in these datasets: https://github.com/johnhcasallasl/T0/blob/MWGR2_2016/etc/ProdOfflineConfiguration.py#L286

**Comment by ebohorqu** [comment]
Maybe we also should leave "defaultRecoTimeout =  48 * 3600" instead "defaultRecoTimeout =  48 * 3600 * 100"

**Comment by johnhcasallasl** [comment]
Done. Thanks for checking!

**Pull request merged**
