### PR TITLE
Replay test of CMSSW_12_4_5_patch1

### PR DESCRIPTION
**Pull request by fabiocos**
# Replay Request

**Requestor**  
ORM

**Describe the configuration**  
* Release: CMSSW_12_4_5_patch1
* Run: 356433
* GTs:
   * expressGlobalTag: 124X_dataRun3_Express_v4
   * promptrecoGlobalTag: 124X_dataRun3_Prompt_v4
   * alcap0GlobalTag: 124X_dataRun3_Prompt_v4
* Additional changes:

**Purpose of the test**  
CMSSW_12_4_5_patch1 meant for HLT, T0 do not strictly need to updated, but testing to be prepared

**T0 Operations cmsTalk thread**
https://cms-talk.web.cern.ch/t/replay-testing-cmssw-12-4-5-patch1/13687

### CODE REVIEW

**Comment by fabiocos** [comment]
test syntax please

**Comment by fabiocos** [comment]
run replay please

**Comment by fabiocos** [comment]
Since HLT is experiencing problems with this patch release and is planning to roll it back to CMSSW_12_4_5, and likely more developments and fixes will be needed, I am not sure this replay makes really sense as it is. In case it might be possibly combined with other tests, like those of AlCa for PPS. 
@francescobrivio @tvami up to you to decide and follow with next ORM

**Comment by francescobrivio** [comment]
Based on the [release notes for 12_4_5_patch1](https://github.com/cms-sw/cmssw/releases/tag/CMSSW_12_4_5_patch1), this patch doesn't really contain anything useful for AlCa, so this replay can be closed from the AlCa point of view, thanks Fabio!

**Comment by fabiocos** [comment]
@francescobrivio it is clear that it has nothing specific for alca, just if ORM wants to give it a try anyway, this might be used instead of CMSSW_12_4_5 for next AlCa tests.

**Pull request closed without merging**
