### PR TITLE
Replay test with 11_2_2

### PR DESCRIPTION
**Pull request by silviodonato**
This PR is to try the automatic replay.
Here I'm using 11_2_2. 
I will use 11_2_2_patch1 for the actual replay in few hours.

### CODE REVIEW

**Comment by silviodonato** [comment]
ah, probably I have to use https://github.com/CMSTier0

**Comment by drkovalskyi** [comment]
You did it all correctly

**Comment by silviodonato** [comment]
> Can one of the admins verify this patch?

@drkovalskyi I was confused by this message.
Perhaps it needs some time to see that I'm member of https://github.com/CMSTier0

**Comment by germanfgv** [comment]
Hi @silviodonato. Everthing seems fine. I'm also a bit confused by that comment, but maybe you are right and it just needs time. Please, go ahead and request the replay when the new release is ready. I'll take a look at our Jenkins config to make sure everything is fine.

**Pull request closed without merging**
