### PR TITLE
Pypi packaging script

### PR DESCRIPTION
**Pull request by gkfthddk**
PyPI packaging script for T0 repository.
It is based on WMCore packaging script, https://github.com/dmwm/WMCore/wiki/DMWM-Packaging-with-PyPi .

T0, T0Component modules in `src/python` are packaged and `bin`, `etc` are uploaded to PyPI project.
Version of package is ordered by git tags.

If you want to upload package 

make ~/.pypirc
```
[pypi]
repository: https://upload.pypi.org/legacy/
username: username

[testpypi]
repository = https://test.pypi.org/legacy/
username: username
```
And

```
$ virtualenv pypibuild
$ source pypibuild/bin/activate
$ git clone https://github.com/dmwm/T0.git
$ cd T0
$ git fetch && git fetch --tags
$ git checkout <tag>
$ sh etc/build_pypi_packages.sh
```

### CODE REVIEW

**Comment by gkfthddk** [comment]
test this please

**Comment by gkfthddk** [comment]
run replay please

**Comment by tvami** [comment]
This PR has been here for a while, what is the status of it? Shall it be closed @germanfgv ?

**Comment by gkfthddk** [comment]
Drop PyPI issue for now, It's not urgent.

**Pull request closed without merging**
