### PR TITLE
Replay testing CMSSW_12_5_1 with Run3 data

### PR DESCRIPTION
**Pull request by germanfgv**
# Replay Request

**Requestor**  
Team or person that requests this replay

**Describe the configuration**  
* Release: CMSSW_12_5_1
* Run: 360788
* GTs:
   * expressGlobalTag: 124X_dataRun3_Express_v6
   * promptrecoGlobalTag: 124X_dataRun3_Prompt_v5
   * alcap0GlobalTag:
* Additional changes:

**Purpose of the test**  
Test 12_5_1 in preparation for HI tests

**T0 Operations cmsTalk thread**  
[Preparation of Tier0 replay on 2018 HI data](https://cms-talk.web.cern.ch/t/feedback-needed-preparation-of-tier0-replay-on-2018-hi-data/16678)

### CODE REVIEW

**Comment by germanfgv** [comment]
@malbouis @francescobrivio could you please provide the GTs for Run3 pp collisions?

**Comment by francescobrivio** [comment]
Dear @germanfgv,
for pp collisions please use:
 - Express: 124X_dataRun3_Express_v6
 - Prompt: 124X_dataRun3_Prompt_v5
 
 these GTs will be put in production shortly (as soon as we have a new 12_4_X), but they are effectively identical to the ones already in production:
 - [Express diff wrt v5](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_dataRun3_Express_v5/124X_dataRun3_Express_v6)
 - [Prompt diff wrt v4](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/124X_dataRun3_Prompt_v4/124X_dataRun3_Prompt_v5)

**Comment by germanfgv** [comment]
The replay can be followed here:
https://monit-grafana.cern.ch/d/t_jr45h7k/cms-tier0-replayid-monitoring?orgId=11&var-Bin=5m&var-ReplayID=221031110715&var-JobType=All&var-WorkflowType=All

**Comment by germanfgv** [comment]
We have this error with Express jobs:
```
cmsRun1
Fatal Exception (Exit Code: 8022)
An exception of category 'FatalRootError' occurred while
   [0] Calling InputSource::readRun_
   Additional Info:
      [a] Fatal Root Error: @SUB=TH1Merger::CheckForDuplicateLabels
Histogram gemChamberVFATBX0GENeg11 has duplicate labels in the x axis. Bin contents will be merged in a single bin
```

**Comment by francescobrivio** [comment]
> We have this error with Express jobs:
> 
> ```
> cmsRun1
> Fatal Exception (Exit Code: 8022)
> An exception of category 'FatalRootError' occurred while
>    [0] Calling InputSource::readRun_
>    Additional Info:
>       [a] Fatal Root Error: @SUB=TH1Merger::CheckForDuplicateLabels
> Histogram gemChamberVFATBX0GENeg11 has duplicate labels in the x axis. Bin contents will be merged in a single bin
> ```

This looks like a DQM issue (@emanueleusai @rvenditti @syuvivida), but @germanfgv do you have any additional detail on this crash?

**Comment by mmusich** [comment]
> This looks like a DQM issue

it looks like the sort of thing you might want to open a cmssw github issue about (and contact GEM developers there)

**Comment by germanfgv** [comment]
@francescobrivio here you can find the logs of the job:
```
/afs/cern.ch/user/c/cmst0/public/PausedJobs/HIReplay2022/job_244/job/WMTaskSpace/cmsRun1
```

**Comment by germanfgv** [comment]
We also have a similar error in PromptReco Merge:
```
2022-10-31 13:57:52,820:CRITICAL:CMSSW:Error message: An exception of category 'FatalRootError' occurred while
   [0] Calling InputSource::readRun_
   Additional Info:
      [a] Fatal Root Error: @SUB=TH1Merger::CheckForDuplicateLabels
Histogram gemChamberVFATBX0GENeg11 has duplicate labels in the x axis. Bin contents will be merged in a single bin
```

Logs and tarbal are here:
```
/afs/cern.ch/user/c/cmst0/public/PausedJobs/HIReplay2022/job_487/job/WMTaskSpace/cmsRun1
```

**Comment by rvenditti** [comment]
> We have this error with Express jobs:
> 
> ```
> cmsRun1
> Fatal Exception (Exit Code: 8022)
> An exception of category 'FatalRootError' occurred while
>    [0] Calling InputSource::readRun_
>    Additional Info:
>       [a] Fatal Root Error: @SUB=TH1Merger::CheckForDuplicateLabels
> Histogram gemChamberVFATBX0GENeg11 has duplicate labels in the x axis. Bin contents will be merged in a single bin
> ```

Sorry for the stupid question: in this step that is failing, you are merging DQMIO before harvesting, or just doing harvesting?

**Comment by germanfgv** [comment]
@rvenditti  these are merging jobs, run before harvesting

**Comment by germanfgv** [comment]
I'll close this PR. New configuration is being tested in #4778

**Pull request closed without merging**
