### PR TITLE
Add missing physics skims to some PDs

### PR DESCRIPTION
**Pull request by germanfgv**
T0

**Describe the configuration**  
* Release:  CMSSW_12_4_9
* Run: [356824](https://cmsoms.cern.ch/cms/runs/report?cms_run=356824)
* GTs:
   * expressGlobalTag: 124X_dataRun3_Express_v5
   * promptrecoGlobalTag: 124X_dataRun3_Prompt_v4
   * alcap0GlobalTag: 124X_dataRun3_Prompt_v4
* Additional changes:

**Purpose of the test**  
Test update to physics skims as requested in here: [CMSTZ-1010](https://its.cern.ch/jira/browse/CMSTZ-1010)

**T0 Operations cmsTalk thread**  
No post

### CODE REVIEW

**Comment by germanfgv** [comment]
@sam7k9621 Here is the PR. Checking [autoSkim.py](https://github.com/cms-sw/cmssw/blob/master/Configuration/Skimming/python/autoSkim.py), I see that `EXODisappTrk` is also included in JetMET. Should I add this to our config too?

**Comment by sam7k9621** [comment]
@germanfgv please include it, thank you for the notification!

**Comment by germanfgv** [comment]
The replay test is running. If successful,  I'll move this to production. It should be finished tonight.

https://monit-grafana.cern.ch/d/t_jr45h7k/cms-tier0-replayid-monitoring?orgId=11&var-Bin=5m&var-JobType=All&var-ReplayID=220920105849&var-WorkflowType=All&from=now-24h&to=now&refresh=5s

**Comment by germanfgv** [comment]
The replay finished without issues. We will make the update in the production configuration.

**Pull request merged**
