### PR TITLE
Replay test with CMSSW_11_3_0_pre6

### PR DESCRIPTION
**Pull request by silviodonato**
First test of CMSSW_11_3_X for the MWGR#4 (2-4 June).
There will be a CMSSW_11_3_0 ~next week, but it would be good to test CMSSW_11_3_X in advance, but I'm not sure if we can make a test with a prerelease.
I've also updated the global tag to https://github.com/cms-sw/cmssw/blob/master/Configuration/AlCa/python/autoCond.py

### CODE REVIEW

**Comment by silviodonato** [comment]
run replay please

**Comment by germanfgv** [comment]
Hi  @silviodonato I'll look into why the replay did not started.

**Comment by silviodonato** [comment]
> Hi @silviodonato I'll look into why the replay did not started.

Thank you. It is possible that we need to mark `CMSSW_11_3_0_pre6` as production release before running the test.

**Comment by germanfgv** [comment]
The problem was an authentication issue with Rucio, due to a problem with our private key. I have fixed it and will redeploy the replay.

> > Hi @silviodonato I'll look into why the replay did not started.
> 
> Thank you. It is possible that we need to mark `CMSSW_11_3_0_pre6` as production release before running the test.

**Comment by germanfgv** [comment]
run replay please

**Comment by boudoul** [comment]
Dear colleagues , could you please announce replays  on HN as soon as they are launched , thank you

**Comment by germanfgv** [comment]
@silviodonato All PromptReco jobs from the replay are paused with the following error:
```
INFO:root:Subprocess stderr was:
None
INFO:root:Executing CMSSW. args: ['/bin/bash', '/srv/job/WMTaskSpace/cmsRun1/cmsRun1-main.sh', '', 'slc7_amd64_gcc900', 'scramv1', 'CMSSW', 'CMSSW_11_3_0_pre6', 'FrameworkJobReport.xml', 'cmsRun', 'PSet.py', '', '', '']
CRITICAL:root:Error running cmsRun
{'arguments': ['/bin/bash', '/srv/job/WMTaskSpace/cmsRun1/cmsRun1-main.sh', '', 'slc7_amd64_gcc900', 'scramv1', 'CMSSW', 'CMSSW_11_3_0_pre6', 'FrameworkJobReport.xml', 'cmsRun', 'PSet.py', '', '', '']}
CMSSW Return code: 8001

CRITICAL:root:Error message: An exception of category 'EventSetupConflict' occurred while
   [0] Calling beginJob
Exception Message:
two EventSetup Sources want to deliver type="EcalTPGTPMode" label=""
 from record EcalTPGTPModeRcd. The two providers are 
1) type="PoolDBESSource" label="EcalTPGDoubleWeightRecords"
2) type="PoolDBESSource" label="GlobalTag"
Please either
   remove one of these Sources
   or find a way of configuring one of them so it does not deliver this data
   or use an es_prefer statement in the configuration to choose one.
CRITICAL:root:CMSDefaultHandler Diagnostic Handler invoked
```

**Comment by germanfgv** [comment]
@silviodonato, @francescobrivio pointed out on [HyperNews](https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/2212/1/1.html) that this issue was solved with [CMSSWPR33509](https://github.com/cms-sw/cmssw/pull/33509), which was not included in CMSSW_11_3_0_pre6. Should we follow his suggestion and go back to the previous Global Tags, or do you prefer to fix the CMSSW release instead?

**Comment by silviodonato** [comment]
Moved to https://github.com/dmwm/T0/pull/4572
I've opened a new PR because the new PR uses 11_3_0

**Comment by silviodonato** [comment]
@germanfgv I'm sorry of the confusion between the two PRs. It would have been better to use a different branch. You can stop the tests related to this PR.

**Comment by germanfgv** [comment]
> @germanfgv I'm sorry of the confusion between the two PRs. It would have been better to use a different branch. You can stop the tests related to this PR.

It's ok. The only replay running right now is the one testing #4572.

**Pull request closed without merging**
