### PR TITLE
Replay of CMSSW_11_2_2_patch1

### PR DESCRIPTION
**Pull request by silviodonato**
All the PRs expected for the MWGR#2 are already merged.
Let's try a replay of CMSSW_11_2_2_patch1

### CODE REVIEW

**Comment by silviodonato** [comment]
The release is ready https://github.com/cms-sw/cmssw/releases/CMSSW_11_2_2_patch1
and visible from CVFMS
```
[sdonato@lxplus7118 ~]$ scram list -a | grep CMSSW_11_2_2_patch1

  CMSSW           CMSSW_11_2_2_patch1        
                                         --> /cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_11_2_2_patch1

```

**Comment by silviodonato** [comment]
@drkovalskyi @germanfgv please have a look if I'm missing something, the test failed.
Perhaps the original code was not updated to the code in the latest Replay (CMSSW_11_1_4 instead of 11_2_1_patch2)

**Comment by germanfgv** [comment]
@silviodonato We have some issues with our unit tests so their results are not reliable right now. For the moment, please don't worry about them. It's great that the test were triggered! Please feel free to continue with the request for a replay

**Comment by silviodonato** [comment]
run replay please

**Comment by drkovalskyi** [comment]
Despite what Jenkins says about failures, the replay itself seems to be Ok according to Monit. @germanfgv any ideas what's going on?

**Comment by germanfgv** [comment]
@drkovalskyi Repack jobs are running normally, but Express and PromptReco jobs are paused. I'm not sure why yet. 

On another issue, the replay is using 11_1_4 because I didn't include anything about version override in the tutorial. I'll modify the standar replay configuration to override previous CMSSW version with the value of `defaultCMSSWVersion['default']`

**Comment by silviodonato** [comment]
FYI. I cannot open https://its.cern.ch/jira/browse/CMSTZDEV-640, while for instance I can open https://its.cern.ch/jira/browse/CMSTZ-900. My account is sdonato. I'm not eager to

**Comment by germanfgv** [comment]
Hi @silviodonato, 
The reason Express and PromptReco workflows failed is because the configuration specifies `slc7_amd64_gcc820` as the scram architecture instead `slc7_amd64_gcc900`, so scram was unable to find the release. WE should have receive a more insightful error report about this. We will look into that.

**Comment by drkovalskyi** [comment]
We should also add some kind of test before running the replay that checks for release availability.

**Comment by silviodonato** [comment]
run replay please

**Comment by silviodonato** [comment]
I moved the code to `slc7_amd64_gcc900`

**Comment by germanfgv** [comment]
@silviodonato As you can see from the error report, the issue with the paused jobs is that they are trying to use 11_1_4 instead of 11_2_2. This is a consequence of the mapping specified in line 135 of the configuration file. I made a modification to that mapping and committed it to your Repo (sorry for committing directly, but for some reason, GH was failing every time I tried to create a new branch and PR). I'll launch another replay with this new mapping. In the future, you won't have to be concern about this issue.

**Comment by germanfgv** [comment]
run replay please

**Comment by germanfgv** [comment]
@silviodonato Finally, this error seems like something meaningful.  Is this an expected error when processing runs 337240 and 337234 with this version of CMSSW? These runs were initially processed with CMSSW_11_1_3

**Comment by silviodonato** [comment]
Thanks, @germanfgv . Could you update the baseline .py file?

**Comment by silviodonato** [comment]
The latest replay should be
https://its.cern.ch/jira/browse/CMSTZ-908

**Comment by germanfgv** [comment]
@silviodonato Thank for your help with this test. We will change a few things in the baseline file to make this easier. Of course we need to keep the baseline file up to date with the most recent requested replay, I'm sorry it was outdated for this test. We'll merge the current test configuration and get back to you when we are ready to test this again. In the meantime, I think we can close this PR. Do you agree?

**Comment by silviodonato** [comment]
Sure!

**Pull request closed without merging**
