### PR TITLE
Test CMSSW_11_2_4

### PR DESCRIPTION
**Pull request by silviodonato**
Test CMSSW_11_2_4 for the MWGR#3

### CODE REVIEW

**Comment by germanfgv** [comment]
Hi @silviodonato. It is necessary to change run numbers and global tags, as requested by Andreas and Sal. I'll create a PR to your repo with the necessary changes.

**Comment by germanfgv** [comment]
> Hi @silviodonato. It is necessary to change run numbers and global tags, as requested by Andreas and Sal. I'll create a PR to your repo with the necessary changes.

Sorry, @silviodonato. I missclick and committed directly. In any case, the configuration file is ready to be tested. Could you please comment the trigger phrase to start the replay? just to make sure that everything is still working.

**Comment by silviodonato** [comment]
run replay please

**Comment by silviodonato** [comment]
> > Hi @silviodonato. It is necessary to change run numbers and global tags, as requested by Andreas and Sal. I'll create a PR to your repo with the necessary changes.
> 
> Sorry, @silviodonato. I missclick and committed directly. In any case, the configuration file is ready to be tested. Could you please comment the trigger phrase to start the replay? just to make sure that everything is still working.

No problem at all. In general it would be better if we keep master branch updated. Anyway, it is not big problem given that you fixed it very quickly!

**Comment by silviodonato** [comment]
@boudoul @amassiro @rappoccio @qliphy this is the Replay test of CMSSW_11_2_4 for the MWGR#3

**Comment by boudoul** [comment]
Thanks !

**Comment by boudoul** [comment]
It is important for this replay to be advertised with the config used on Tier0 HN (as usual for replays) , thank you

**Comment by germanfgv** [comment]
> > > Hi @silviodonato. It is necessary to change run numbers and global tags, as requested by Andreas and Sal. I'll create a PR to your repo with the necessary changes.
> > 
> > 
> > Sorry, @silviodonato. I missclick and committed directly. In any case, the configuration file is ready to be tested. Could you please comment the trigger phrase to start the replay? just to make sure that everything is still working.
> 
> No problem at all. In general it would be better if we keep master branch updated. Anyway, it is not big problem given that you fixed it very quickly!

The master branch was up to date with the latest successful requested replay. But new replay request usually ask for new runs and GTs to be tested. So, I'm not sure what are you suggesting. I don't think we should update master branch with runs and GTs that don't have been tested.

**Comment by drkovalskyi** [comment]
> > No problem at all. In general it would be better if we keep master branch updated. Anyway, it is not big problem given that you fixed it very quickly!
> 
> The master branch was up to date with the latest successful requested replay. But new replay request usually ask for new runs and GTs to be tested. So, I'm not sure I understand what you are suggesting. I don't think we should update master branch with runs and GTs that haven't been tested.

Actually the runs were processed by Tier0, so they are tested by production. So we can update the run each time we settle on a new reference run.

**Comment by silviodonato** [comment]
> There are 5 paused jobs in the replay.

@germanfgv @drkovalskyi does it mean there are problems? Is the test still running?

**Comment by germanfgv** [comment]
> > There are 5 paused jobs in the replay.
> 
> @germanfgv @drkovalskyi does it mean there are problems? Is the test still running?

The test is still going. These 5 paused jobs where due known memory issues with NanoDST Repack jobs (jobs asking for ~1.4GB, surpassing the 1GB limit). We already have a workaround for them, so I fixed them and the replay is ongoing.

In any case, I will report on those memory issues as we would like to find a better solution for them.

**Comment by silviodonato** [comment]
> **Container Tests**
> JIRA URL : https://its.cern.ch/jira/browse/CMSTZDEV-648
> Tier0_REPLAY v266 DMWM-T0-PR-test-job on vocms047.cern.ch. Test CMSSW_11_2_4
> **There are 5 paused jobs in the replay.** List of Paused job below.
> Cache directory : Exit code
> /data/tier0/docker/container1/srv/wmagent/current/install/tier0/JobCreator/JobCache/
> └─Repack_Run338628_StreamNanoDST_Tier0_REPLAY_2020_v2104081011_210408_1012/Repack/JobCollection_3_0/job_2749 : None
> └─Repack_Run340220_StreamNanoDST_Tier0_REPLAY_2020_v2104081011_210408_1012/Repack/JobCollection_11_0/
> └─job_9271 : None
> └─job_9272 : None
> └─Repack_Run338628_StreamNanoDST_Tier0_REPLAY_2020_v2104081011_210408_1012/Repack/JobCollection_13_0/job_9463 : None
> └─Repack_Run338714_StreamNanoDST_Tier0_REPLAY_2020_v2104081011_210408_1012/Repack/JobCollection_15_0/job_9465 : None
> 
> There are only 5 memory errors, Will check again after 5 hours.
> **There are 6 paused jobs in the replay.** List of Paused job below.
> Cache directory : Exit code
> /data/tier0/docker/container1/srv/wmagent/current/install/tier0/JobCreator/JobCache/Express_Run338714_StreamExpressCosmics_Tier0_REPLAY_2020_v2104081011_210408_1012/Express/
> └─JobCollection_6_0/
> └─job_5019 : None
> └─job_4305 : None
> └─job_5258 : None
> └─JobCollection_6_1/
> └─job_5290 : None
> └─job_5403 : None
> └─job_5449 : None
> 
> _Return None : 1 job(s)_
> #Error message ==========
> 
> #====================
> 
> _Return None : 1 job(s)_
> #Error message ==========
> 
> #====================
> 
> _Return None : 1 job(s)_
> #Error message ==========
> 
> #====================
> 
> _Return None : 1 job(s)_
> #Error message ==========
> 
> #====================
> 
> Replay was closed by puased job

@germanfgv @drkovalskyi could you point us the errors?

**Comment by drkovalskyi** [comment]
It's in the JIRA ticket: https://its.cern.ch/jira/browse/CMSTZDEV-648. It has only memory issues that are well known.

**Comment by silviodonato** [comment]
> It's in the JIRA ticket: https://its.cern.ch/jira/browse/CMSTZDEV-648. It has only memory issues that are well known.

Perfect, thank you! I cannot open https://its.cern.ch/jira/browse/CMSTZDEV-648, I'm getting "You can't view this issue.It may have been deleted or you don't have permission to view it." Closing this PR.

**Comment by drkovalskyi** [comment]
You have to login. It's a weird "feature" of JIRA. It's accessible to all CMS members.

**Comment by boudoul** [comment]
Hello thanks all ! 
For the JIRA, I cannot open either (I'm logged in) 
for the information on Tier0 HN , for the future, could you please open a dedicated thread for the replay (not answering a thread announcing a meeting or so) ? thank you

**Comment by drkovalskyi** [comment]
We will do. Meanwhile I have fixed the issue with JIRA. Please retry.

**Pull request closed without merging**
