### PR TITLE
test CMSSW_12_0_3_patch2

### PR DESCRIPTION
**Pull request by qliphy**
# Replay Request

Test CMSSW_12_0_3_patch2, with configurations following
https://github.com/dmwm/T0/pull/4630

**Requestor**  
Qiang Li [ORP]

**Describe the configuration**  
* Release:  CMSSW_12_0_3_patch2
* Run: 345915
* GTs:
   * expressGlobalTag:   120X_dataRun3_Express_v2
   * promptrecoGlobalTag:  120X_dataRun3_Prompt_v2
   * alcap0GlobalTag:  120X_dataRun3_Prompt_v2
* Additional changes:  None

**Purpose of the test**  
Test CMSSW_12_0_3_patch2, with a few minor fixes on top of 12_0_3_patch1

**T0 Operations HyperNews thread**  
https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/2315.html

### CODE REVIEW

**Comment by qliphy** [comment]
@germanfgv @tvami  
Let me know if it looks good to you.

**Comment by qliphy** [comment]
run replay please

**Comment by tvami** [comment]
I think this can be closed too, CMSSW_12_0_3_patch2 is the production release now

**Comment by germanfgv** [comment]
As reported in https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/2315.html, the replay finished succesfully. The PR was moved to production in #4634

**Pull request closed without merging**
