### PR TITLE
Replay test of CMSSW_12_4_6

### PR DESCRIPTION
**Pull request by tyjyang**
# Replay Request

**Requestor**  
ORM

**Describe the configuration**  
* Release: CMSSW_12_4_6
* Run: 356824
* GTs:
   * expressGlobalTag: 124X_dataRun3_Express_v4
   * promptrecoGlobalTag: 124X_dataRun3_Prompt_v4
   * alcap0GlobalTag: 124X_dataRun3_Prompt_v4
* Additional changes:

**Purpose of the test**  
This release contains the [fix](https://github.com/cms-sw/cmssw/pull/38989) to be deployed on HLT.

**T0 Operations cmsTalk thread**

### CODE REVIEW

**Comment by francescobrivio** [comment]
test syntax please

**Comment by tyjyang** [comment]
run replay please

**Comment by jeyserma** [comment]
Replay started.
https://monit-grafana.cern.ch/d/t_jr45h7k/cms-tier0-replayid-monitoring?orgId=11&var-Bin=5m&var-ReplayID=220809163743&var-JobType=All&var-WorkflowType=All
Proc version v916374

**Comment by tyjyang** [comment]
replay completed successfully

**Pull request closed without merging**
