### PR TITLE
Replay configuration for CMSSW_14_0_0 using #4914 as starting point

### PR DESCRIPTION
**Pull request by fabiocos**
# Replay Request

**Requestor**  
ORM

**Describe the configuration**  
* Release: CMSSW_14_0_0
* Run: 369998, 359688, 375832
* GTs:
   * expressGlobalTag: 140X_dataRun3_Express_v2
   * promptrecoGlobalTag: 140X_dataRun3_Prompt_v2
* Additional changes:
   * Express: Add TkAlZMuMu and PromptCalibProdSiPixelAliHGComb
   * HLTPhysics*: Add TkAlV0s producer

**Purpose of the test**  
Initial test of CMSSW_14_0_0, based on the configuration used for the earlier replay of 14_0_0_pre3 #4914 , pending full release validation

**T0 Operations cmsTalk thread**  
[Tier0 Operations cmsTalk Forum](https://cms-talk.web.cern.ch/t/replay-request-with-cmssw-14-0-0/35240)

### CODE REVIEW

**Comment by germanfgv** [comment]
run replay please

**Comment by fabiocos** [comment]
@germanfgv do you understand the reason for the failure? The Jenkins console output does not sound that informative to me

**Comment by fabiocos** [comment]
@germanfgv is the T0 supposed to have el8_amd64_gcc11 as default in next future, and we should take care of this for each possible new version to be tested? I expect a 13_3_2_patch2 very soon for instance

**Comment by germanfgv** [comment]
> @germanfgv is the T0 supposed to have el8_amd64_gcc11 as default in next future, and we should take care of this for each possible new version to be tested? I expect a 13_3_2_patch2 very soon for instance

As it works now, we define a default architecture, and we specify any exceptions that we might need. This is particularly important for a replay like this which is using runs from different years. In Production, it is usually enough to define a default architecture, except in cases in which we are moving from one architecture to the other (e.g. last week).

We will move towards automatically verifying the proper architecture while creating the workflows, to avoid this problems in the future.

**Comment by germanfgv** [comment]
Continuing 14_0_0 tests in #4924

**Pull request closed without merging**
