### PR TITLE
Add EcalPhiSymByRun for ECAL ALCANANO test

### PR DESCRIPTION
**Pull request by tvami**
# Replay Request

**Requestor**  

AlCaDB

**Describe the configuration**  
* Release: ~CMSSW_12_3_0~, ~CMSSW_12_4_0_pre3~, ~CMSSW_12_3_2~, CMSSW_12_4_3
* Run: 346512
* GTs:
   * expressGlobalTag: ~123X_dataRun3_Express_v5~,`124X_dataRun3_Express_v3`
   * promptrecoGlobalTag: ~123X_dataRun3_Prompt_v6~,`124X_dataRun3_Prompt_v3`
   * alcap0GlobalTag: ~123X_dataRun3_Prompt_v6~, `124X_dataRun3_Prompt_v3`
* Additional changes:

**Purpose of the test**  

To test the `ALCANANO` for ECAL. The Replay is really stripped down to run the ECAL stream alone. 

**T0 Operations cmsTalk thread**  

Will provide soon
[Tier0 Operations cmsTalk Forum](https://cms-talk.web.cern.ch/c/offcomp/compops/tier0/210?)

### CODE REVIEW

**Comment by tvami** [comment]
In the relvals we have these special commands:
https://github.com/cms-sw/cmssw/blob/master/Configuration/PyReleaseValidation/python/relval_steps.py#L2263-L2270

Chatting with Marco I understand this means that we need a new scenario for this to be able to run at T0 :(

**Comment by tvami** [comment]
I made a new scenario
https://github.com/cms-sw/cmssw/pull/37627

**Comment by tvami** [comment]
`CMSSW_12_4_0_pre3` is out:
https://cms-talk.web.cern.ch/t/development-release-cmssw-12-4-0-pre3-now-available/9562/1
so this can be launched any time

**Comment by tvami** [comment]
The replay is ongoing and can be followed at 
https://monit-grafana.cern.ch/d/t_jr45h7k/cms-tier0-replayid-monitoring?orgId=11&var-Bin=5m&var-ReplayID=220421182132&var-JobType=All&var-WorkflowType=All

**Comment by tvami** [comment]
Since `CMSSW_12_3_2` is soon out, I'll make a commit to change to that

**Comment by tvami** [comment]
run replay please

**Comment by tvami** [comment]
The replay fails with this msg
```
(Exit Code: 8006)
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 346512 lumi: 1 event: 387150 stream: 5
   [1] Running path 'pathALCARECOEcalPhiSymByRun'
   [2] Calling method for module EcalPhiSymRecHitProducerRun/'ALCARECOEcalPhiSymRecHitProducerRun'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: edm::SortedCollection<EcalRecHit,edm::StrictWeakOrdering<EcalRecHit> >
Looking for module label: ecalRecHit
Looking for productInstanceName: EcalRecHitsEB
```
which seems to be due to the costumization not taking effect -- investigating

**Comment by tvami** [comment]
The replay in progress can be followed here
https://monit-grafana.cern.ch/d/t_jr45h7k/cms-tier0-replayid-monitoring?orgId=11&var-Bin=5m&var-ReplayID=220505153443&var-JobType=All&var-WorkflowType=All

**Comment by tvami** [comment]
Outcome
```
Fatal Exception (Exit Code: 8006)
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 346512 lumi: 1 event: 683762 stream: 6
   [1] Running path 'dqmoffline_step'
   [2] Calling method for module HBHENoiseFilterResultProducer/'HBHENoiseFilterResultProducer'
Exception Message:
 could not find HcalNoiseSummary.
   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.
```

So I was wrong and the T0 config doesn't have more control about the DQM step than the ConfigBuilder packages. PR to CMSSW will follow soon

**Comment by tvami** [comment]
`CMSSW_12_4_0_pre4` is out, so let's test with that
https://cms-talk.web.cern.ch/t/development-release-cmssw-12-4-0-pre4-now-available/10458/1

**Comment by tvami** [comment]
run replay please

**Comment by germanfgv** [comment]
I deployed this replay in onw of our machines. You can follow its progress here:
https://monit-grafana.cern.ch/d/t_jr45h7k/cms-tier0-replayid-monitoring?orgId=11&var-Bin=5m&var-ReplayID=220516113210&var-JobType=All&var-WorkflowType=All

**Comment by tvami** [comment]
That is surprising. Doing
```
voms-proxy-init -rfc -voms cms -valid 192:00

cmsrel CMSSW_12_4_0_pre4
cd CMSSW_12_4_0_pre4/src
cmsenv
git cms-addpkg Configuration/DataProcessing
python3 Configuration/DataProcessing/test/RunPromptReco.py --scenario AlCaPhiSymEcal_Nano --reco --global-tag 123X_dataRun3_Prompt_v6 --lfn=file:/eos/cms/tier0/store/backfill/1/data/Tier0_REPLAY_2022/AlCaPhiSym/RAW/v91/000/346/512/00000/4887980a-dac3-48e0-be08-d99284f75c5b.root --alcareco EcalPhiSymByRun
cmsRun -e RunPromptRecoCfg.py
```
used to work.

Now I cant do it bc the RAW file is not available anymore. The repack output of this replay is supposed to be in
```
 ls /eos/cms/tier0/store/backfill/1/data/Tier0_REPLAY_2022/AlCaPhiSym/RAW/v214/000/346/512/00000/
```
no? Why is this empty?

**Comment by germanfgv** [comment]
@tvami It's because of this section in your configuration:
```python
for dataset in DATASETS:
    addDataset(tier0Config, dataset,
               do_reco=True,
               raw_to_disk=True,
               disk_node="T2_CH_CERN",
               alca_producers=["EcalPhiSymByRun"],
               scenario=alcaPhiSymEcalScenario)
```
specificaly [line 244](
https://github.com/dmwm/T0/blob/dbf6e04309109f83d8792de51f81d9892e6cbfe7/etc/ReplayOfflineConfiguration.py#L244), where you specify that the dataset is supposed tobe stored in `T2_CH_CERN` (as opposed to the default `T0_CH_CERN_Disk`).

You can find the file in:
```
$ ll /eos/cms/store/backfill/1/data/Tier0_REPLAY_2022/AlCaPhiSym/RAW/v214/000/346/512/00000/
total 83M
-rw-r--r--. 1 phedex zh 83M May 16 12:47 93a1f119-2267-4a1a-b8c2-1f34a06feaea.root
```

**Comment by tvami** [comment]
Thanks @germanfgv !

I can reproduce the error.
```
python3 Configuration/DataProcessing/test/RunPromptReco.py --scenario AlCaPhiSymEcal_Nano --reco --global-tag 123X_dataRun3_Prompt_v6 --lfn=file:/eos/cms/store/backfill/1/data/Tier0_REPLAY_2022/AlCaPhiSym/RAW/v214/000/346/512/00000/93a1f119-2267-4a1a-b8c2-1f34a06feaea.root --alcareco EcalPhiSymByRun
```

This is the same thing that worked in https://github.com/cms-sw/cmssw/pull/37854
Is there a way we can bring back the file `/eos/cms/tier0/store/backfill/1/data/Tier0_REPLAY_2022/AlCaPhiSym/RAW/v91/000/346/512/00000/4887980a-dac3-48e0-be08-d99284f75c5b.root`?

**Comment by tvami** [comment]
It does work with 
> $ edmEventSize -v -a /eos/cms/tier0/store/backfill/1/data/Tier0_REPLAY_2022/AlCaPhiSym/RAW/v23/000/346/512/00000/19319bf3-e8d5-4741-86d5-01ee9eb2b3a9.root

> Wondering if the repack is done differently w.r.t that one.
@germanfgv any insights for this?

**Comment by germanfgv** [comment]
@tvami can you try with the following file:
```
/afs/cern.ch/user/g/ggiraldo/public/Compression/AlCaPhiSym/Run346512
```
It was repacked using the new compression configuration but without dropping products

**Comment by tvami** [comment]
I confirm that the `RunPromptReco.py` works with this output!

**Comment by tvami** [comment]
run replay please

**Comment by germanfgv** [comment]
Prompt reco jobs failed with the following error:
```
cmsRun1
Misc. CMSSW error (Exit Code: 99109)
Error in CMSSW: 99109
'ConfigSection' object has no attribute 'nanoout'
 Adding last 25 lines of CMSSW stderr:
WARNING: In non-interactive mode release checks e.g. deprecated releases, production architectures are disabled.
WARNING: There already exists /srv/job/WMTaskSpace/cmsRun1/CMSSW_12_3_4_patch1 area for SCRAM_ARCH slc7_amd64_gcc10.

 Adding last 25 lines of CMSSW stdout:
dropped waiting message count 0
TimeReport> Time report complete in 37.0227 seconds
 Time Summary: 
 - Min event:   0.000219822
 - Max event:   0.840925
 - Avg event:   0.00285219
 - Total loop:  8.53768
 - Total init:  25.8566
 - Total job:   37.0227
 - EventSetup Lock: 0
 - EventSetup Get:  0
 Event Throughput: 563.15 ev/s
 CPU Summary: 
 - Total loop:     13.8831
 - Total init:     19.0606
 - Total extra:    0
 - Total children: 5.96143
 - Total job:      35.2265
 Processing Summary: 
 - Number of Events:  4808
 - Number of Global Begin Lumi Calls:  1
 - Number of Global Begin Run Calls: 1

Complete
process id is 575 status is 0
```

**Comment by tvami** [comment]
> 'ConfigSection' object has no attribute 'nanoout'

OK, finally something that really has to do with the purpose of this development.
Now, can you point me to where this `ConfigSection` lives?

**Comment by simonepigazzini** [comment]
I guess the question is for T0. For reference, in CMSSW the nanoout module is added here:

https://github.com/cms-sw/cmssw/blob/master/Calibration/EcalCalibAlgos/python/EcalPhiSymRecoSequence_cff.py#L172

This is actually adding the flat nano output, which we might want to drop for T0 processing.

**Comment by drkovalskyi** [comment]
Tier0 doesn't explicitly support NanoAOD and all the associated flat commands. We can only run part of the code storing everything as EDM.

**Comment by germanfgv** [comment]
Here you can follow the latest replay with this PR:

https://monit-grafana.cern.ch/d/t_jr45h7k/cms-tier0-replayid-monitoring?orgId=11&var-Bin=5m&var-ReplayID=220630100106&var-JobType=All&var-WorkflowType=All

**Comment by germanfgv** [comment]
The error is this:
```
2022-06-30 12:07:53,154:ERROR:ExecuteMaster:Exception is 'ConfigSection' object has no attribute 'nanoout'
2022-06-30 12:07:53,154:ERROR:ExecuteMaster:Traceback: 
2022-06-30 12:07:53,155:ERROR:ExecuteMaster:Traceback (most recent call last):
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/ExecuteMaster.py", line 141, in doExecution
    executionObject.execute()
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/Executors/CMSSW.py", line 346, in execute
    self.report.addInfoToOutputFilesForStep(stepName=self.stepName, step=self.step)
  File "/srv/job/WMCore.zip/WMCore/FwkJobReport/Report.py", line 1173, in addInfoToOutputFilesForStep
    fileInfo(fileReport=aFile, step=step, outputModule=module)
  File "/srv/job/WMCore.zip/WMCore/FwkJobReport/FileInfo.py", line 67, in __call__
    return self.processFile(filename = pfn,
  File "/srv/job/WMCore.zip/WMCore/FwkJobReport/FileInfo.py", line 85, in processFile
    output = getattr(step.output.modules, outputModule)
AttributeError: 'ConfigSection' object has no attribute 'nanoout'
```
I think we have seen this before, is that right @tvami ?

**Comment by tvami** [comment]
We did, and I actually fixed that, but it seems that never entered CMSSW_12_3_6, ok https://github.com/cms-sw/cmssw/releases/CMSSW_12_3_6

Let's redo it with 12_4_1

**Comment by germanfgv** [comment]
Ok, I'l retry

**Comment by tvami** [comment]
> Ok, I'l retry

You'll also need to change GT when moving to other CMSSW, so let me make a commit in a minute

**Comment by tvami** [comment]
@germanfgv done in https://github.com/dmwm/T0/pull/4664/commits/409c74456d0e3c860f40c0b4dd8ea1545522794d please go ahead with the test

**Comment by germanfgv** [comment]
Here: 
https://monit-grafana.cern.ch/d/t_jr45h7k/cms-tier0-replayid-monitoring?orgId=11&var-Bin=5m&var-ReplayID=220701093300&var-JobType=All&var-WorkflowType=All

**Comment by jhonatanamado** [comment]
Hi @tvami , the last configuration shows a single paused job with the following error:
```
2022-07-01 12:50:30,930:INFO:Scram:Creating a subprocess to run the PSet setup.
2022-07-01 12:50:30,930:INFO:Scram:Also recording SCRAM command-line related output.
2022-07-01 12:50:30,933:INFO:Scram:    Invoking command: cmssw_wm_create_process.py --output_pkl /srv/job/WMTaskSpace/cmsRun1/PSet.pkl --funcname alcaSkim --funcargs /srv/job/WMTaskSpace/cmsRun1/process_funcArgs.json
2022-07-01 12:50:35,209:INFO:Scram:Subprocess stdout was:\nb\'Failed to load process from Scenario AlCaPhiSymEcal_Nano (<Configuration.DataProcessing.Impl.AlCaPhiSymEcal_Nano.AlCaPhiSymEcal_Nano object at 0x2b4a9a4c9d30>).
"/cvmfs/cms.cern.ch/share/overrides/bin/cmssw_wm_create_process.py", line 144, "/cvmfs/cms.cern.ch/share/overrides/bin/cmssw_wm_create_process.py", line 135, 
process=create_process(args, func_args)File "/cvmfs/cms.cern.ch/share/overrides/bin/cmssw_wm_create_process.py", line 97, in create_process
raise ex File "/cvmfs/cms.cern.ch/share/overrides/bin/cmssw_wm_create_process.py", line 93, in create_process
process = my_func(*call_func_args, **func_args) File "/cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw/CMSSW_12_4_1/python/Configuration/DataProcessing/Scenario.py", line 104, in alcaSkim
raise NotImplementedError(msg)
NotImplementedError: Scenario Implementation AlCaPhiSymEcal_Nano\\nDoes not contain an implementation for alcaSkim
2022-07-01 12:50:35,210:INFO:Scram:Subprocess stderr was: None 
2022-07-01 12:50:35,210:ERROR:SetupCMSSWPset:Error running scram process.
```
Logs and tarballs are in `/afs/cern.ch/user/c/cmst0/public/Tarballs_Replays/PR4664/job_628`

**Comment by tvami** [comment]
Latest monitoring link: https://monit-grafana.cern.ch/d/t_jr45h7k/cms-tier0-replayid-monitoring?orgId=11&var-Bin=5m&var-ReplayID=220718161806&var-JobType=All&var-WorkflowType=All

**Comment by jhonatanamado** [comment]
Replay finished without issues. [Output](https://monit-grafana.cern.ch/d/t_jr45h7k/cms-tier0-replayid-monitoring?orgId=11&var-Bin=5m&var-ReplayID=220718161806&var-JobType=All&var-WorkflowType=All&viewPanel=29) data is 
```
/AlCaPhiSym/Tier0_REPLAY_2022-EcalPhiSymByRun-PromptReco-v213/ALCARECO#7e1efd1c-b165-41f4-84dc-8d3e56c83825
/AlCaPhiSym/Tier0_REPLAY_2022-PromptReco-v213/AOD#ebcc04a1-7c5d-423b-958d-1a41cc6f8aa3
/AlCaPhiSym/Tier0_REPLAY_2022-PromptReco-v213/MINIAOD#dd676ad1-c8e7-443f-a30a-867dba0de21f
/AlCaPhiSym/Tier0_REPLAY_2022-v213/RAW#e6863153-553b-40bc-9f97-323a3e63f915
```

**Comment by tvami** [comment]
Oh yeah! That's new! @simonepigazzini please have a look at the output, thanks!

**Comment by tvami** [comment]
@jhonatanamado please post the tarballs, thanks!

**Comment by jhonatanamado** [comment]
Output data for the latest changes (https://github.com/dmwm/T0/pull/4664/commits/49d8f5303958138759e914cc329783da75f36d8e) are:
```
/AlCaPhiSym/Tier0_REPLAY_2022-EcalPhiSymByRun-PromptReco-v1907/ALCARECO#16a8f798-65bd-4541-8b3c-126d84a3d920
/AlCaPhiSym/Tier0_REPLAY_2022-PromptReco-v1907/AOD#93ad1b20-76b6-4706-af3e-986970b15e9c
/AlCaPhiSym/Tier0_REPLAY_2022-PromptReco-v1907/MINIAOD#a51bc6dd-9fe0-4d57-abcd-f9f3b67e5377
/AlCaPhiSym/Tier0_REPLAY_2022-v1907/RAW#1819c59d-1506-4849-a294-5db7b2bb863d
```

**Comment by tvami** [comment]
@simonepigazzini 

```
Dataset: [/AlCaPhiSym/Tier0_REPLAY_2022-EcalPhiSymByRun-PromptReco-v1907/ALCARECO](https://cmsweb.cern.ch/das/request?input=dataset%3D%2FAlCaPhiSym%2FTier0_REPLAY_2022-EcalPhiSymByRun-PromptReco-v1907%2FALCARECO&instance=prod/global)
Dataset size: 67224426 (67.2MB) Number of blocks: 1 Number of events: 2575197 Number of files: 1 Creation time: 2022-07-20 03:27:08 Cross section: 0 Physics group: NoGroup Status: VALID Type: data
```
[Release](https://cmsweb.cern.ch/das/request?instance=prod/global&input=release+dataset%3D%2FAlCaPhiSym%2FTier0_REPLAY_2022-EcalPhiSymByRun-PromptReco-v1907%2FALCARECO), [Blocks](https://cmsweb.cern.ch/das/request?instance=prod/global&input=block+dataset%3D%2FAlCaPhiSym%2FTier0_REPLAY_2022-EcalPhiSymByRun-PromptReco-v1907%2FALCARECO), [Files](https://cmsweb.cern.ch/das/request?instance=prod/global&input=file+dataset%3D%2FAlCaPhiSym%2FTier0_REPLAY_2022-EcalPhiSymByRun-PromptReco-v1907%2FALCARECO), [Runs](https://cmsweb.cern.ch/das/request?instance=prod/global&input=run+dataset%3D%2FAlCaPhiSym%2FTier0_REPLAY_2022-EcalPhiSymByRun-PromptReco-v1907%2FALCARECO), [Configs](https://cmsweb.cern.ch/das/request?instance=prod/global&input=config+dataset%3D%2FAlCaPhiSym%2FTier0_REPLAY_2022-EcalPhiSymByRun-PromptReco-v1907%2FALCARECO), [Parents](https://cmsweb.cern.ch/das/request?instance=prod/global&input=parent+dataset%3D%2FAlCaPhiSym%2FTier0_REPLAY_2022-EcalPhiSymByRun-PromptReco-v1907%2FALCARECO), [Children](https://cmsweb.cern.ch/das/request?instance=prod/global&input=child+dataset%3D%2FAlCaPhiSym%2FTier0_REPLAY_2022-EcalPhiSymByRun-PromptReco-v1907%2FALCARECO), [Sites](https://cmsweb.cern.ch/das/request?instance=prod/global&input=site+dataset%3D%2FAlCaPhiSym%2FTier0_REPLAY_2022-EcalPhiSymByRun-PromptReco-v1907%2FALCARECO), [Physics Groups](https://cmsweb.cern.ch/das/request?instance=prod/global&input=group+dataset%3D%2FAlCaPhiSym%2FTier0_REPLAY_2022-EcalPhiSymByRun-PromptReco-v1907%2FALCARECO) [XSDB](https://cms-gen-dev.cern.ch/xsdb/?searchQuery=DAS=AlCaPhiSym) Sources: dbs3 [show](javascript:ToggleTag('id_62d7aacdaff476a3f35347ef', 'link_62d7aacdaff476a3f35347ef'))

This time, it doesnt seem to be empty

**Comment by simonepigazzini** [comment]
Hi,

the files are not empty but do not contain the collection we are supposed to save there. All the trees (Event, LS, Run) are empty, in the sense that only each tree trivial branches are stored.

simone

**Comment by tvami** [comment]
test syntax please

**Comment by tvami** [comment]
https://monit-grafana.cern.ch/d/t_jr45h7k/cms-tier0-replayid-monitoring?orgId=11&var-Bin=5m&var-ReplayID=220729165850&var-JobType=All&var-WorkflowType=All

**Comment by tvami** [comment]
replay is failing with
```
2022-07-29 22:15:20,845:INFO:Report:addOutputFile method fileRef: , whole tree: {}
2022-07-29 22:15:20,883:ERROR:ExecuteMaster:Exception occured when executing step
2022-07-29 22:15:20,883:ERROR:ExecuteMaster:Exception is 'ConfigSection' object has no attribute 'nanooutedm'
2022-07-29 22:15:20,883:ERROR:ExecuteMaster:Traceback: 
2022-07-29 22:15:20,886:ERROR:ExecuteMaster:Traceback (most recent call last):
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/ExecuteMaster.py", line 141, in doExecution
    executionObject.execute()
  File "/srv/job/WMCore.zip/WMCore/WMSpec/Steps/Executors/CMSSW.py", line 335, in execute
    self.report.addInfoToOutputFilesForStep(stepName=self.stepName, step=self.step)
  File "/srv/job/WMCore.zip/WMCore/FwkJobReport/Report.py", line 1170, in addInfoToOutputFilesForStep
    fileInfo(fileReport=aFile, step=step, outputModule=module)
  File "/srv/job/WMCore.zip/WMCore/FwkJobReport/FileInfo.py", line 67, in __call__
    return self.processFile(filename = pfn,
  File "/srv/job/WMCore.zip/WMCore/FwkJobReport/FileInfo.py", line 85, in processFile
    output = getattr(step.output.modules, outputModule)
AttributeError: 'ConfigSection' object has no attribute 'nanooutedm'
```

**Comment by tvami** [comment]
> replay is failing with

Just to be clear, I have no idea what to do with the failure above

**Comment by tvami** [comment]
I created this JIRA ticket: https://its.cern.ch/jira/browse/CMSTZ-1002

**Comment by tvami** [comment]
I'm also closing this PR, as at this point more serious development is needed

**Pull request closed without merging**
