### PR TITLE
Replay configuration requested by AlCaDB

### PR DESCRIPTION
**Pull request by germanfgv**
Replay configuration requested by Francesco for AlCaDB
The request can be found in https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/2231.html

### CODE REVIEW

**Comment by germanfgv** [comment]
run replay please to HN

**Comment by germanfgv** [comment]
run replay please to HN

**Comment by germanfgv** [comment]
@gkfthddk There are still issues with replay tracking.

**Comment by germanfgv** [comment]
The replay is still running. I'll report on its progress here and in HN (https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/2231.html).

**Comment by francescobrivio** [comment]
@germanfgv as reported by Marco in https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/2231/1/1/1/1.html there was a bug in the alcareco prompt matrix that I originally proposed (https://twiki.cern.ch/twiki/bin/view/CMS/AlCaRecoMatrix#Prompt_Configuration_AN7) which has now been fixed.
The change is minor: "SingleMu" --> "SingleMuon".

**Comment by germanfgv** [comment]
Yes, I can update the config, but this is just because we have not been able to create PromptReco workflows due to this error with the CMSSW release.

```
2021-06-23 23:24:22,623:140381993195264:INFO:BaseWorkerThread:Worker thread <T0Component.Tier0Feeder.Tier0FeederPoller.Tier0FeederPoller object at 0x7fad45734b90> started
2021-06-23 23:24:47,298:140381993195264:ERROR:StdBase:About to raise exception Can't find physics skim LogError in CMSSW_12_0_0_pre2
2021-06-23 23:24:47,425:140381993195264:ERROR:BaseWorkerThread:Error in worker algorithm (1):
Backtrace:
  <T0Component.Tier0Feeder.Tier0FeederPoller.Tier0FeederPoller object at 0x7fad45734b90> b'<@========== WMException Start ==========@>
Exception Class: WMSpecFactoryException
Message: Can't find physics skim LogError in CMSSW_12_0_0_pre2
        ModuleName : WMCore.WMSpec.StdSpecs.StdBase
        MethodName : raiseValidationException
        ClassInstance : None
        FileName : /data/srv/wmagent/2.2.4/sw/slc7_amd64_gcc630/cms/t0/2.2.4/lib/python2.7/site-packages/WMCore/WMSpec/StdSpecs/StdBase.py
        ClassName : None
        LineNumber : 923
        ErrorNr : 0
```
> @germanfgv as reported by Marco in https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/2231/1/1/1/1.html there was a bug in the alcareco prompt matrix that I originally proposed (https://twiki.cern.ch/twiki/bin/view/CMS/AlCaRecoMatrix#Prompt_Configuration_AN7) which has now been fixed.
> The change is minor: "SingleMu" --> "SingleMuon".

**Comment by francescobrivio** [comment]
Hi @germanfgv yes please update the configuration and let us know when the replay can be repeated.
Sorry again for the inconvenience!

**Comment by francescobrivio** [comment]
Hi @germanfgv sorry to bother, any news about the replay with the updated configuration?

**Comment by germanfgv** [comment]
hi @francescobrivio. Sorry for the delays with this replay. Right now we have paused jobs in the ExpressPhysics workflow. The error we got is the following:
```
An exception of category 'CTPPSGeometry' occurred while
   [0] Processing global begin Run run: 324841
   [1] Calling method for module CTPPSDiamondDQMSource/'ctppsDiamondDQMSource'
Exception Message:
Not found detector with ID 2054160384, i.e. subDet=5 arm=0 station=1 rp=6
```

**Comment by francescobrivio** [comment]
> hi @francescobrivio. Sorry for the delays with this replay. Right now we have paused jobs in the ExpressPhysics workflow. The error we got is the following:
> 
> ```
> An exception of category 'CTPPSGeometry' occurred while
>    [0] Processing global begin Run run: 324841
>    [1] Calling method for module CTPPSDiamondDQMSource/'ctppsDiamondDQMSource'
> Exception Message:
> Not found detector with ID 2054160384, i.e. subDet=5 arm=0 station=1 rp=6
> ```

Hi @germanfgv! no worries about the delay, it was the weekend afterall! 
Are there log/tarballs available for this error?
We'll try to take a look later today (after my talk at the RC workshop).

**Comment by germanfgv** [comment]
> > hi @francescobrivio. Sorry for the delays with this replay. Right now we have paused jobs in the ExpressPhysics workflow. The error we got is the following:
> > ```
> > An exception of category 'CTPPSGeometry' occurred while
> >    [0] Processing global begin Run run: 324841
> >    [1] Calling method for module CTPPSDiamondDQMSource/'ctppsDiamondDQMSource'
> > Exception Message:
> > Not found detector with ID 2054160384, i.e. subDet=5 arm=0 station=1 rp=6
> > ```
> 
> Hi @germanfgv! no worries about the delay, it was the weekend afterall!
> Are there log/tarballs available for this error?
> We'll try to take a look later today (after my talk at the RC workshop).

Yes @francescobrivio , you can find logs and tarball in `/afs/cern.ch/user/c/cmst0/public/PausedJobs/TestPCL/job_3876`

**Comment by germanfgv** [comment]
@francescobrivio I have a question. Are you interested in us running PromptReco workflows aside SingleMuon or can I remove them from the test?

**Comment by francescobrivio** [comment]
> @francescobrivio I have a question. Are you interested in us running PromptReco workflows aside SingleMuon or can I remove them from the test?

Hi @germanfgv at the moment we are only interested in the SingleMuon PromptReco, other workflows can be removed.

**Comment by francescobrivio** [comment]
@germanfgv sorry for the late update.
Just FYI I think we understood (and probably fixed) the `CTPPSGeometry` error, but more exceptions related to PPS arise. 
I'm investigating with PPS experts and will let you know asap!

**Comment by germanfgv** [comment]
@francescobrivio Great! Let me know when you need additional tests.

**Comment by francescobrivio** [comment]
Hi @germanfgv! After debugging with PPS experts we concluded PPS workflow is not yet ready to be tested in the replay.
Hence the `PromptCalibProdPPS` should be removed from the ExpressPhysics configuration (https://github.com/dmwm/T0/pull/4581/files#diff-4d2c96d3e15eb107f3aec15b5259355379fad0c475f704ed3a3cf8720cf94684R229) before resubmitting the replay, sorry for the inconvenience!

I'm also wondering about the point raised by Matti in https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/2231/1/1/1/1/1/1/1/1/1/1.html: if we run the replay again are we going to see this same error?
Going back in the HN I found a proposed solution from Dirk https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/2187/1/1/1/1/2/1/1/1/1/2/1.html , but I don't know if it's still applicable or not....

**Comment by germanfgv** [comment]
Hi @francescobrivio. The run 324841 uses CMSSW_10_1_10 as default repacking version. That CMSSW release is not available in for `slc7_amd64_gcc900` which is the only SCRAM arch in which we can find CMSSW_12_0_0. Our agent works specifying a single scram arch for every job. It would probably be possible to modify our code to run such a test, but sadly, as Dima pointed out in [here](https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/2231/2.html), we are currently working in other developments for Run3 and this kind of test is out of the usual T0 scope.

I'll try to rerun the test usin CMSSW_11_1_0_pre8 for repacking, as this one is available in `slc7_amd64_gcc900` and ahould work with the old dataformat, but that's as far as we can go.

> Hi @germanfgv! After debugging with PPS experts we concluded PPS workflow is not yet ready to be tested in the replay.
> Hence the `PromptCalibProdPPS` should be removed from the ExpressPhysics configuration (https://github.com/dmwm/T0/pull/4581/files#diff-4d2c96d3e15eb107f3aec15b5259355379fad0c475f704ed3a3cf8720cf94684R229) before resubmitting the replay, sorry for the inconvenience!
> 
> I'm also wondering about the point raised by Matti in https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/2231/1/1/1/1/1/1/1/1/1/1.html: if we run the replay again are we going to see this same error?
> Going back in the HN I found a proposed solution from Dirk https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/2187/1/1/1/1/2/1/1/1/1/2/1.html , but I don't know if it's still applicable or not....

**Comment by germanfgv** [comment]
run replay please

**Comment by francescobrivio** [comment]
> Monitoring for replay is closed.
> Log ====
> Jira cookie is lost
> 
> ==== End

@germanfgv thanks for re-launching the replay! 
Does this message imply an error in the replay or it is just related to the monitoring?

**Comment by francescobrivio** [comment]
This can be closed as it is superseded by #4602

**Pull request closed without merging**
