### PR TITLE
Replay for CMSSW_13_3_3

### PR DESCRIPTION
**Pull request by fabiocos**
# Replay Request

**Requestor**  
ORM

**Describe the configuration**  
* Release: CMSSW_13_3_3
* Run: 369998, 375832, 376727
* GTs:
   * expressGlobalTag: 133X_dataRun3_Express_v2
   * promptrecoGlobalTag: 133X_dataRun3_Prompt_v2
* Additional changes:

**Purpose of the test**  
Test of CMSSW_13_3_3, requested by ALCA in view of CRAFT data taking.

**T0 Operations cmsTalk thread**  
[Tier0 Operations cmsTalk Forum](https://cms-talk.web.cern.ch/c/offcomp/compops/tier0/210?)

### CODE REVIEW

**Comment by fabiocos** [comment]
@saumyaphor4252 @mmusich In this replay request I assumed no further change besides the release, containing the PR you requested. Please comment in case more is desired on your side.

**Comment by mmusich** [comment]
> Please comment in case more is desired on your side.

I guess that if we could run it on a recent cosmics run @ 0T from 2024 it would prove the point of the patch.

**Comment by fabiocos** [comment]
run replay please

**Comment by mmusich** [comment]
@fabiocos 

> the processing of run 376727 appears completed in WMStats, you may already check its outcome

can you please post the output datasets?

**Comment by mmusich** [comment]
For starters I don't see uploads from the PCL in that run in the reply https://cms-conddb.cern.ch/cmsDbBrowser/logs/condition_uploader_logs/Prep/2024-02-16/2024-02-23/None/None/Run376727/None/None/None/any (which is a good sign)

**Comment by mmusich** [comment]
> can you please post the output datasets?

nevermind, I got them myself.
Dataset of interest is `/StreamExpressCosmics/Tier0_REPLAY_2023-PromptCalibProdSiStripLA-Express-v20150257/ALCAPROMPT`.

Inspected runs:
   * 376727: http://tinyurl.com/24swdk3c => no change in output (as expected since there is no Tracker in data-taking)

**Comment by fabiocos** [comment]
@mmusich thanks for the check and the confirmation, provided everything closes correctly as I expect, I propose to move the T0 to CMSSW_13_3_3 on Monday, in time for CRAFT.

**Pull request merged**
