### PR TITLE
Enable prompt AlCaLumiPixelsCountsPrompt

### PR DESCRIPTION
**Pull request by jhonatanamado**
add alca_producers and enable prompt for this PD and change alcaLumiPixelsScenario for Run3

### CODE REVIEW

**Comment by jhonatanamado** [comment]
GTs needs to be validated and check backward compatibility with the previous `alcaLumiPixelsScenario`

**Comment by tvami** [comment]
> GTs needs to be validated and check backward compatibility with the previous `alcaLumiPixelsScenario`

I'm not really sure what this means. The new scenario `AlCaLumiPixels_Run3` is for Run-3 only, while `AlCaLumiPixels` is for Run-2. There is a new stream for Run-3 as well, so this is by definition not backward compatible.

**Comment by tvami** [comment]
I should also say that the prerequisite of this prompt to work properly is to change the express workflow, as done in https://github.com/dmwm/T0/pull/4650 here:
https://github.com/tvami/T0/blob/cfa2efad806fcade9c100ef7074c2fe2e1da663a/etc/ReplayOfflineConfiguration.py#L230-L253

**Comment by tvami** [comment]
> Are all the streamers and PDs needed for Run3?

Depends on the fill type, for special fills (Van der Meer scans) that happens 1-2 times a year, all the numbers are needed, while in default fills we only have one stream. @jbenitez could comment more

**Comment by benitezj** [comment]
> > Are all the streamers and PDs needed for Run3?
> 
> Depends on the fill type, for special fills (Van der Meer scans) that happens 1-2 times a year, all the numbers are needed, while in default fills we only have one stream. @benitezj could comment more

hi all.
 I think to avoid missing any data lets process both streams (Prompt and Express) for ALL fills.  

Thanks.
Jose

(it is true we don't need the ALCARECO's of the vdM fills, but doesn't hurt to have them and maybe we can use them for some check.)

**Comment by tvami** [comment]
Hi @benitezj maybe I misunderstood @jhonatanamado , but I thought his question was about the fact that there are a lot of numbers after `AlCaLumiPixelsCountsPrompt`
Screen Shot 2022-05-03 at 08 52 42
 
My understanding was that these numbers only come in for the vdM fills, is that correct?

**Comment by germanfgv** [comment]
these changes are being included in #4677

**Pull request closed without merging**
