### PR TITLE
Replay configuration for CMSSW_12_4_4

### PR DESCRIPTION
**Pull request by mdmorris**
# Replay Request

**Requestor**  
ORM

**Describe the configuration**  
* Release: CMSSW_12_4_4
* Run: 356005, 356069
* GTs:
   * expressGlobalTag: 124X_dataRun3_Express_v4
   * promptrecoGlobalTag: 124X_dataRun3_Prompt_v4
   * alcap0GlobalTag: 124X_dataRun3_Prompt_v4
* Additional changes: EXOCSCCluster added to physics_skim when 12_4_4 is introduced

**Purpose of the test**  
Testing for new release CMSSW_12_4_4 and Global Tag changes

### CODE REVIEW

**Comment by tvami** [comment]
test syntax please

**Comment by germanfgv** [comment]
Thank you @mdmorris. I'll deploy the replay. Please also create a CMS Talk thread about it in the Tier0-operations forum.

**Comment by germanfgv** [comment]
You can follow progress of the replay here:
https://monit-grafana.cern.ch/d/t_jr45h7k/cms-tier0-replayid-monitoring?orgId=11&var-Bin=5m&var-ReplayID=220727165206&var-JobType=All&var-WorkflowType=All

**Comment by germanfgv** [comment]
The replay finished successfully. Merging to master in #4728

**Pull request closed without merging**
