### PR TITLE
Replay for testing SiStripsAlcaNano

### PR DESCRIPTION
**Pull request by francescobrivio**
# Replay Request

**Requestor**  
Francesco Brivio for AlCa/TrackingPOG/TrackerDPG.

**Describe the configuration**  
* Release: CMSSW_12_2_3_patch1
* Run: 345755 (2021 CRAFT - 6.5h long)
* GTs:
   * expressGlobalTag: 122X_dataRun3_Express_v3
   * promptrecoGlobalTag: 122X_dataRun3_Prompt_v3
   * alcap0GlobalTag: 122X_dataRun3_Prompt_v3
* Additional changes:
  * Removed all the PDs except for Cosmics (to save computing resources)
  * Ignored all the express streams (to save computing resources)
  * Added `SiStripCalCosmicsNano` producer to the `alca_producers` for the Cosmics dataset

**Purpose of the test**  
This replay is intended to test the `SiStripCalCosmicsNano` producer which has been included in relvals since last year and produces NANOEDMAOD outputs. This was discussed at the [PPD general meeting on the 24<sup>th</sup> of March](https://indico.cern.ch/event/1137466/#b-455328-discussion-of-nano-fo).

**T0 Operations cmsTalk thread** 
N/A

FYI @mmusich @tvami @malbouis @rappoccio @jordan-martins

### CODE REVIEW

**Comment by francescobrivio** [comment]
@germanfgv @jhonatanamado please check that the ignored streams are correctly set-up.

**Comment by tvami** [comment]
Hi @francescobrivio I think you should *not* ignore
```
ignoreStream(tier0Config, "ExpressCosmics")
```
since this is a Cosmics replay

**Comment by francescobrivio** [comment]
> Hi @francescobrivio I think you should _not_ ignore
> 
> ```
> ignoreStream(tier0Config, "ExpressCosmics")
> ```
> 
> since this is a Cosmics replay

Yea I thought about that, but in the cosmics menu from last year (in [this JIRA](https://its.cern.ch/jira/browse/CMSHLT-2166?focusedCommentId=4022223&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4022223)) I see that the `Cosmics` dataset is actually under the `Physics` stream.

**Comment by tvami** [comment]
These are the available streamer files for this run
```
/eos/cms/store/t0streamer/Data/Calibration/000/345/755/:
/eos/cms/store/t0streamer/Data/ExpressCosmics/000/345/755/:
/eos/cms/store/t0streamer/Data/NanoDST/000/345/755/:
/eos/cms/store/t0streamer/Data/Physics/000/345/755/:
```

so 
(1) many of the things you ignore are not even there, I dont really know if that's a problem or not (usually it's easy to ignore things that dont exists haha :P )
(2) ok so `ExpressCosmics` is really to just make the Express output, right? Wouldn't it be still go to run Cosmics express just before we run the Cosmics prompt?

**Comment by francescobrivio** [comment]
> (2) ok so `ExpressCosmics` is really to just make the Express output, right? Wouldn't it be still go to run Cosmics express just before we run the Cosmics prompt?

Ok I'll add it back just to be on the safe side.

**Comment by tvami** [comment]
run replay please

**Comment by germanfgv** [comment]
@francescobrivio @tvami We will need to wait a bit on this one, while we wrap up other of our stuff. @jhonatanamado  will check the configuration and then enable free the slot for running the replay.

**Comment by jhonatanamado** [comment]
Hello @francescobrivio , This is the dataflow for Tier0:
Screen Shot 2022-04-07 at 2 49 09 AM
So the run 345755 has `Calibration,ExpressCosmics, NanoDST, Physics`. As you mentioned before `ExpressCosmics` will produce only `ExpressCosmics` datasets and indeed, `Cosmics` is under the `Physics` stream.
Now if only the `Cosmics` PD is in the configuration, and express is not relevant for this test, this will return something like the following:
```
/Cosmics/Tier0-Replay-$version/RAW -> Comes from Repack (Other dataset may be repacked)
/Cosmics/Tier0-Replay-PromptReco-$version/DATATIER (Datatiers such as AOD,DQMIO)
/Cosmics/Tier0-Replay-$alca_producers-PromptReco-$version/ALCARECO
/Cosmics/Tier0-Replay-$physics_skims-PromptReco-$version/DATATIERS (Datatiers in relation to physics_skims such as Raw-Reco,User)
```
If you want to produce NANOAOD Tier, this is not supported by Tier0.

The proposed solution is to have the NanoAOD being produced from the Production side, this involving  PdmV action and not from Tier0. More information about this here -> https://its.cern.ch/jira/browse/CMSTZ-969 

Please let me know if the changes for this PR make sense t and if it's still valid to trigger this replay.

**Comment by mmusich** [comment]
Hi @jhonatanamado @francescobrivio 

> If you want to produce NANOAOD Tier, this is not supported by Tier0.

can you clarify if by `NANOAOD` here, you mean flat ROOT trees, or also `NANOEDMAOD`? Because `SiStripCalCosmicsNano` is producing the latter, e.g. you can manipulate files produced in the RelVals with edm tools:

```console
$ edmEventSize -v -a root://eoscms.cern.ch//eos/cms/store/relval/CMSSW_12_3_0_pre6/ExpressCosmics/NANOAOD/SiStripCalCosmicsNano-123X_dataRun3_Prompt_v5_RelVal_2021GR5-v1/10000/8eb88cf8-2135-4ed9-943b-8072e969d117.root

File root://eoscms.cern.ch//eos/cms/store/relval/CMSSW_12_3_0_pre6/ExpressCosmics/NANOAOD/SiStripCalCosmicsNano-123X_dataRun3_Prompt_v5_RelVal_2021GR5-v1/10000/8eb88cf8-2135-4ed9-943b-8072e969d117.root Events 122384
Branch Name | Average Uncompressed Size (Bytes/Event) | Average Compressed Size (Bytes/Event) 
cluster_rhlocalx 61.5461 54.0402
cluster_localx 61.5458 53.9959
cluster_localdirx 61.5464 53.6986
cluster_barycenter 61.5466 50.8498
cluster_localdirz 61.5464 48.334
cluster_localdiry 61.5464 47.856
cluster_rhlocalxerr 61.5465 45.3174
cluster_variance 61.5461 42.4047
cluster_rawid 61.5456 16.2422
cluster_nstrips 61.5459 5.8036
track_eta 8.00134 4.25883
track_chi2ndof 8.00196 4.09537
track_phi 8.00134 3.91699
track_pt 8.00122 3.5832
event 8.00766 1.98982
track_hitsvalid 8.00208 1.24375
cluster_trackindex 61.5462 1.1073
ncluster 4.00775 0.676069
ntrack 4.00788 0.0486665
luminosityBlock 4.00841 0.0375049
run 4.00743 0.0125997
``` 
Is the `ALCARECO` for the data-tier:
```
/Cosmics/Tier0-Replay-$alca_producers-PromptReco-$version/ALCARECO
```

hard-coded in the Tier-0 configuration?
Because `SiStripCalCosmicsNano` declared as datatier `NANOAOD`: 

https://github.com/cms-sw/cmssw/blob/bad89902ce8af17f1bba4ceea6a523171ebf3069/Configuration/StandardSequences/python/AlCaRecoStreams_cff.py#L468-L476

e.g. these are the output datasets from relvals.
```
$ dasgoclient -query='dataset dataset=/*/*SiStripCalCosmicsNano*/* status=*'
/ExpressCosmics/CMSSW_12_1_0_pre4-SiStripCalCosmicsNano-121X_dataRun3_Express_v5_RelVal_2021GR5-v1/NANOAOD
/ExpressCosmics/CMSSW_12_1_0_pre4-SiStripCalCosmicsNano-121X_dataRun3_Prompt_v5_RelVal_2021GR5-v1/NANOAOD
/ExpressCosmics/CMSSW_12_1_0_pre5-SiStripCalCosmicsNano-121X_dataRun3_Express_v10_RelVal_2021GR5-v1/NANOAOD
/ExpressCosmics/CMSSW_12_1_0_pre5-SiStripCalCosmicsNano-121X_dataRun3_Prompt_v9_RelVal_2021GR5-v1/NANOAOD
/ExpressCosmics/CMSSW_12_2_0-SiStripCalCosmicsNano-122X_dataRun3_Express_v1_RelVal_2021GR5-v1/NANOAOD
/ExpressCosmics/CMSSW_12_2_0-SiStripCalCosmicsNano-122X_dataRun3_Prompt_v1_RelVal_2021GR5-v1/NANOAOD
/ExpressCosmics/CMSSW_12_2_0_pre2-SiStripCalCosmicsNano-122X_dataRun3_Express_v1_RelVal_2021GR5-v1/NANOAOD
/ExpressCosmics/CMSSW_12_2_0_pre2-SiStripCalCosmicsNano-122X_dataRun3_Prompt_v1_RelVal_2021GR5-v1/NANOAOD
/ExpressCosmics/CMSSW_12_2_0_pre3-SiStripCalCosmicsNano-122X_dataRun3_Express_v1_RelVal_2021GR5-v2/NANOAOD
/ExpressCosmics/CMSSW_12_2_0_pre3-SiStripCalCosmicsNano-122X_dataRun3_Express_v1_rsb_RelVal_2021GR5-v1/NANOAOD
/ExpressCosmics/CMSSW_12_2_0_pre3-SiStripCalCosmicsNano-122X_dataRun3_Prompt_v1_RelVal_2021GR5-v2/NANOAOD
/ExpressCosmics/CMSSW_12_2_0_pre3-SiStripCalCosmicsNano-122X_dataRun3_Prompt_v1_rsb_RelVal_2021GR5-v1/NANOAOD
/ExpressCosmics/CMSSW_12_3_0_pre2-SiStripCalCosmicsNano-122X_dataRun3_Express_v1_RelVal_2021GR5-v1/NANOAOD
/ExpressCosmics/CMSSW_12_3_0_pre2-SiStripCalCosmicsNano-122X_dataRun3_Express_v1_RelVal_2021GR5-v2/NANOAOD
/ExpressCosmics/CMSSW_12_3_0_pre2-SiStripCalCosmicsNano-122X_dataRun3_Prompt_v1_RelVal_2021GR5-v1/NANOAOD
/ExpressCosmics/CMSSW_12_3_0_pre2-SiStripCalCosmicsNano-122X_dataRun3_Prompt_v1_RelVal_2021GR5-v2/NANOAOD
/ExpressCosmics/CMSSW_12_3_0_pre3-SiStripCalCosmicsNano-123X_dataRun3_Express_v1_RelVal_2021GR5-v1/NANOAOD
/ExpressCosmics/CMSSW_12_3_0_pre3-SiStripCalCosmicsNano-123X_dataRun3_Prompt_v1_RelVal_2021GR5-v1/NANOAOD
/ExpressCosmics/CMSSW_12_3_0_pre4-SiStripCalCosmicsNano-123X_dataRun3_Express_v1_RelVal_2021GR5-v1/NANOAOD
/ExpressCosmics/CMSSW_12_3_0_pre4-SiStripCalCosmicsNano-123X_dataRun3_Prompt_v1_RelVal_2021GR5-v1/NANOAOD
/ExpressCosmics/CMSSW_12_3_0_pre5-SiStripCalCosmicsNano-123X_dataRun3_Express_v2_RelVal_2021GR5-v1/NANOAOD
/ExpressCosmics/CMSSW_12_3_0_pre5-SiStripCalCosmicsNano-123X_dataRun3_Prompt_v2_RelVal_2021GR5-v1/NANOAOD
/ExpressCosmics/CMSSW_12_3_0_pre6-SiStripCalCosmicsNano-123X_dataRun3_Prompt_v5_RelVal_2021GR5-v1/NANOAOD
```

but it is by all other means just an `ALCARECO` in EDM format (as any other one), only the event structure is not the usual one.

**Comment by mmusich** [comment]
tagging also @robervalwalsh and @mdelcourt

**Comment by jhonatanamado** [comment]
run replay please

**Comment by francescobrivio** [comment]
@mmusich @robervalwalsh @mdelcourt it seems like in the end the replay did produce some output files for the `SiStripCalCosmicsNano`. The output is in:
```
/eos/cms/tier0/store/backfill/1/data/Tier0_REPLAY_2022/Cosmics/ALCARECO/SiStripCalCosmicsNano-PromptReco-v220/000/345/755/00000
```
Could you please have a look and report here if the files are as expected? Thanks!

**Comment by drkovalskyi** [comment]
Thanks Marco. Please keep us updated. We want to see if it all works they way users want it. When we have a clear picture of all use cases we can start looking into what can be done on Tier0 side to improve the workflow.

**Comment by robervalwalsh** [comment]
After running the `merge` step, I performed some checks comparing to a privately-produced tree(*) for the same run. I found out that a few events (~0.01%) are  present only in either of the two trees. I need to investigate further but it should not have anything to do with the production at Tier-0. It also has no impact in the plots used in the analysis, as can be seen in the attached plot

alcanano_validation


(*) /eos/cms/store/group/dpg_tracker_strip/comm_tracker/Strip/Calibration/calibrationtree/Cosmics21/Craft21/calibTreeNano_345755_0.root

**Comment by francescobrivio** [comment]
Given that this test was successful (pending further checks) I will close this PR.

**Comment by davidlange6** [comment]
> 
> /Cosmics/Tier0-Replay-$alca_producers-PromptReco-$version/ALCARECO
> 
> hard-coded in the Tier-0 configuration?
> Because SiStripCalCosmicsNano declared as datatier NANOAOD:
> 
> https://github.com/cms-sw/cmssw/blob/bad89902ce8af17f1bba4ceea6a523171ebf3069/Configuration/StandardSequences/python/AlCaRecoStreams_cff.py#L468-L476
> 

Calling something that is an edm file as data-tier nanoaod will be very confusing. Why overload the naming scheme of nanoaod? (So far used to denote non-edm formatted data)

**Pull request closed without merging**
