### PR TITLE
Remove deprecated PromptCalibProdPPSDiamondSampic PCL producer

### PR DESCRIPTION
**Pull request by francescobrivio**
# Configuration update

**Requestor**  
Francesco for PPS/AlCaDB

**Describe the configuration**
As requested by @vavati in [slide 6 of the PPS talk](https://indico.cern.ch/event/1377170/contributions/5787920/attachments/2807555/4899882/PPS_alca_workshop_2024.pdf#page=6&zoom=auto,-242,593) at the AlCaDB Workshop on February 26<sup>th</sup> 2024, the `PromptCalibProdPPSDiamondSampic` PCL producer should be removed from production since, starting from 2024, the "Sampic detectors cannot take data in global anymore".

This PR removes the producer from all Tier0 configuration files: prod, replay, HI prod, HI replay.

Since this is a simple removal I don't think we need to run a replay, but I leave the final decision to Tier0 experts and the current ORM: @germanfgv @LinaresToine @mmusich 

**T0 Operations cmsTalk thread**  
https://cms-talk.web.cern.ch/t/update-tier0-configurations-to-remove-unused-promptcalibprodppsalignment-pcl-producer/36772

-----

FYI @vavati @saumyaphor4252 @perrotta @consuegs

### CODE REVIEW

**Comment by francescobrivio** [comment]
test syntax please

**Comment by mmusich** [comment]
@francescobrivio I am confused by the PR title, aren't you removing `PromptCalibProdPPSDiamondSampic` instead?

**Comment by francescobrivio** [comment]
> @francescobrivio I am confused by the PR title, aren't you removing `PromptCalibProdPPSDiamondSampic` instead?

sorry I mistyped everywhere in the PR description...I'll fix it immediately

**Comment by mmusich** [comment]
> sorry I mistyped everywhere in the PR description...I'll fix it immediately

also the cmstalk post :)

**Comment by francescobrivio** [comment]
> > sorry I mistyped everywhere in the PR description...I'll fix it immediately
> 
> also the cmstalk post :)

That I cannot do unfortunately 😭 I dont' have the rights to change the cmstalk post (even if it was posted by me...)

**Comment by mmusich** [comment]
>  PCL producer should be removed from production since, starting from 2024, the "Sampic detectors cannot take data in global anymore".

out of curiosity is this permanent (definitely irrecoverable)? In that case one could even think to remove the underlying code in `cmssw`.

**Comment by francescobrivio** [comment]
> > PCL producer should be removed from production since, starting from 2024, the "Sampic detectors cannot take data in global anymore".
> 
> out of curiosity is this permanent (definitely irrecoverable)? In that case one could even think to remove the underlying code in `cmssw`.

I'm not sure, this is something that only @vavati can confirm.

**Comment by vavati** [comment]
No, the Sampic is still running but only in local. If needed the PCL-like code can be used locally or in the automation.I would prefer to keep it in the release. If it is not against rules.

**Comment by mmusich** [comment]
> If needed the PCL-like code can be used locally or in the automation.I would prefer to keep it in the release. If it is not against rules.

it's not against any rule, it was a suggestion to avoid maintenance overhead. If it's useful, perfectly fine to keep it.

**Pull request merged**
