### PR TITLE
Using WMWorkloadHelper.setTaskEnvironmentVariables to override site config

### PR DESCRIPTION
**Pull request by germanfgv**
Uses changes introduced in https://github.com/dmwm/WMCore/pull/10344 to override the site configuration file used by T0 jobs

### CODE REVIEW

**Comment by germanfgv** [comment]
Path to site local config should be picked up from config.Tier0Feeder

**Comment by germanfgv** [comment]
run replay please

**Comment by germanfgv** [comment]
@jhonatanamado, I think this is ready. Could you take a look at the changes I made?. Let me know if you have any suggestions.

**Comment by jhonatanamado** [comment]
Looks good for me

**Pull request merged**
