### PR TITLE
Replay CMSSW_12_3_5

### PR DESCRIPTION
**Pull request by fabiocos**
# Replay Request

**Requestor**  
ORM

**Describe the configuration**  
* Release: CMSSW_12_3_5
* Run: 352493, 349840, 352705
* GTs:
   * expressGlobalTag: 123X_dataRun3_Express_v6
   * promptrecoGlobalTag: 123X_dataRun3_Prompt_v8
   * alcap0GlobalTag: 123X_dataRun3_Prompt_v8
* Additional changes:

**Purpose of the test**  
Test of various fixes in CMSSW_12_3_5, see https://github.com/cms-sw/cmssw/releases/CMSSW_12_3_5 

**T0 Operations cmsTalk thread**  
[Tier0 Operations cmsTalk Forum](https://cms-talk.web.cern.ch/c/offcomp/compops/tier0/210?)

### CODE REVIEW

**Comment by fabiocos** [comment]
test syntax please

**Comment by fabiocos** [comment]
run replay please

**Comment by fabiocos** [comment]
@GermanGiraldo looking into the Jenkins report it is unclear to me what went wrong:

```
Jira Issue can be found at https://its.cern.ch/jira/browse/CMSTZDEV-746
Traceback (most recent call last):
  File "/data/tier0/docker/monitoringHost/replayWorkflowStatus.py", line 744, in <module>
    main_out=main(calljira)
  File "/data/tier0/docker/monitoringHost/replayWorkflowStatus.py", line 414, in main
    ghcomments=requests.post(prComment,headers=ghheaders,data=json.dumps(ghdata)).json()
  File "/data/tier0/jenkins/jiraReport/lib64/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Build step 'Execute shell' marked build as failure
Archiving artifacts
Setting status of f3f753aafad6c303395638d23b79c33606bcd8bc to FAILURE with url https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-T0-PR-test-job/467/ and message: 'Build finished. '
Setting status of f3f753aafad6c303395638d23b79c33606bcd8bc to FAILURE with url https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-T0-PR-test-job/467/ and message: 'This test has failed.
 '
```

**Comment by fabiocos** [comment]
But according to the replay monitoring, jobs are running:
Screenshot 2022-06-04 at 10 30 33

**Comment by fabiocos** [comment]
According to WMStats there is a complete failure of ```ExpressAlcaSkimwrite_StreamExpress_ALCARECO``` for run 349840.

**Comment by fabiocos** [comment]
it looks like a configuration problem in ```ConfigBuilder.py``` related to the change of names

**Comment by fabiocos** [comment]
I believe I understand the problem, the change of names of ALCARECO in CMSSW need to be propagated to the T0 configuration, otherwise there is a name mismatch causing the problem. The issue should appear only on run 352493 (collisions configuration), no need to test for this issue the other runs, which are using the cosmics configuration

**Comment by fabiocos** [comment]
I wait for this test to complete, if cosmics are ok I will rerun a new replay with an updated T0 configuration only for run 352493.

**Comment by tvami** [comment]
>  if cosmics are ok

Neither `PromptCalibProdSiPixelLA` or `PromptCalibProdSiStripHitEfficiency` are meant for Cosmics, so I wouldn't run the replay for that.

If you'd like to test the DBS registration problem, `ALCARECOSiStripCalCosmicsNano` is meant for Cosmics, so that part would make sense.

**Comment by fabiocos** [comment]
@tvami indeed 353493 is a collision run, this is why I want to make a replay only on that. Cosmics are being tested in 349840 (and 353705 even if labeled circulating) and I do not see issues there for the time being.

**Comment by germanfgv** [comment]
This test was continued in #4684

**Pull request closed without merging**
