### PR TITLE
Migrating WBM to OMS in T0 Oracle queries.

### PR DESCRIPTION
**Pull request by vytjan**
Detailed on JIRA:
https://its.cern.ch/jira/browse/CMSTZ-797

### CODE REVIEW

**Comment by vytjan** [comment]
@hufnagel Dirk, do you think this looks reasonable to be merged?
I ran a replay testing this PR and it worked fine.

**Comment by hufnagel** [comment]
I assume you ran a replay with a recent run and it worked. Only thing I would worry about is what if you want to replay an older runs. Do the new OMS database tables contain records for older runs that we potentially want to replay? Even if not it doesn't mean we can't merge this or need to add code to support it. But we should at least be aware if this puts in a age limit for older runs to be replayed (and then we might as well get rid of this old saved streamers for these runs).

**Comment by hufnagel** [comment]
Otherwise this looks good.

**Comment by vytjan** [comment]
OMS database contains all records that are on WBM, starting from the first commissioning runs in 2009 (run 30108, /cdaq/cosmic/commissioning2009/MWGR/MWGR46/HLT_L1override/V2).
So this PR should be fine for any runs and we don't really need any additional age limit, etc.
Thanks for your feedback, Dirk.

**Comment by vytjan** [comment]
test this please

**Comment by germanfgv** [comment]
test this please

**Comment by germanfgv** [comment]
test this please

**Comment by germanfgv** [comment]
run replay please

**Comment by germanfgv** [comment]
replay this please

**Comment by germanfgv** [comment]
run replay please

**Comment by germanfgv** [comment]
test this please

**Comment by germanfgv** [comment]
run replay please

**Pull request merged**
