### PR TITLE
T0 rucio tape

### PR DESCRIPTION
**Pull request by germanfgv**
Testing Tier0 with Rucio transfers to T0 Tape

### CODE REVIEW

**Comment by germanfgv** [comment]
run replay please

**Comment by germanfgv** [comment]
run replay please

**Comment by germanfgv** [comment]
run replay please

**Comment by gkfthddk** [comment]
Host name : vocms047.cern.ch
Container ID : 1
Pull request url : https://github.com/dmwm/T0/pull/4548
Current build at jenkins : https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-T0-PR-test-job/224/.
Jira Issue : https://its.cern.ch/jira/browse/CMSTZDEV-624

**Comment by gkfthddk** [comment]
There are 3415 paused jobs in the replay.

**Comment by gkfthddk** [comment]
Host name : vocms047.cern.ch
Container ID : 1
Pull request url : https://github.com/dmwm/T0/pull/4548
Current build at jenkins : https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-T0-PR-test-job/225/.
Jira Issue : https://its.cern.ch/jira/browse/CMSTZDEV-625

**Comment by gkfthddk** [comment]
There are 155 paused jobs in the replay.

**Comment by gkfthddk** [comment]
Host name : vocms047.cern.ch
Container ID : 1
Pull request url : https://github.com/dmwm/T0/pull/4548
Current build at jenkins : https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-T0-PR-test-job/227/.
Jira Issue : https://its.cern.ch/jira/browse/CMSTZDEV-626

**Comment by gkfthddk** [comment]
There are 1344 paused jobs in the replay.

**Pull request closed without merging**
