### PR TITLE
Replay test of CMSSW_12_4_7

### PR DESCRIPTION
**Pull request by mmusich**
# Replay Request

**Requestor**  
ORM 

**Describe the configuration**  
* Release: CMSSW_12_4_7
* Run: [356824](https://cmsoms.cern.ch/cms/runs/report?cms_run=356824), standard candle run used for previous replays (to cross-check e.g. output of PCL, etc.) [356948](https://cmsoms.cern.ch/cms/runs/report?cms_run=356948) to test solution failure of detailed at https://github.com/cms-sw/cmssw/issues/39026
* GTs:
   * expressGlobalTag: 124X_dataRun3_Express_v5
   * promptrecoGlobalTag: 124X_dataRun3_Prompt_v4
   * alcap0GlobalTag: 124X_dataRun3_Prompt_v4
* Additional changes:
None

**Purpose of the test**  
Test new release that includes bug fixes for the data taking, and some major updates for the local Tracker and for the Tracking code.

**T0 Operations cmsTalk thread**  

https://cms-talk.web.cern.ch/t/replay-testing-cmssw-12-4-7/14062

### CODE REVIEW

**Comment by mmusich** [comment]
@sarafiorendi FYI

**Comment by germanfgv** [comment]
@mmusich Can you pick one of the runs in the replay? we want to avoid unnecessarily large replays as the processing load on T0 is increasing.

**Comment by mmusich** [comment]
>  Can you pick one of the runs in the replay? we want to avoid unnecessarily large replays as the processing load on T0 is increasing.

they are both really short, 30' each. I'd prefer to keep both to test different things.

**Comment by germanfgv** [comment]
Can you please specify the different things being tested with each run?

**Comment by mmusich** [comment]
> Can you please specify the different things being tested with each run?

sure, see PR description, just updated.

**Comment by mmusich** [comment]
also @germanfgv keep in mind this release will feature major updates in Tracker local reco as well tracking, so limiting the amount of testing seems counterproductive to me.

**Comment by germanfgv** [comment]
Yes. I agree with you that the runs are small and the test is important enough. But is good to have a clear reasoning written down.

**Comment by germanfgv** [comment]
The replay has started. You can monitor it's progress here:
https://monit-grafana.cern.ch/d/t_jr45h7k/cms-tier0-replayid-monitoring?orgId=11&var-Bin=5m&var-ReplayID=220818181117&var-JobType=All&var-WorkflowType=All

**Comment by tvami** [comment]
As I see this finished nicely about 6 hours ago

**Comment by germanfgv** [comment]
Changes will e merged in #4746

**Pull request closed without merging**
