### PR TITLE
Replay testing CMSSW_12_4_0

### PR DESCRIPTION
**Pull request by germanfgv**
# Replay Request

**Requestor**  
T0

**Describe the configuration**  
* Release: CMSSW_12_4_0
* Run: 353701, 352929
* GTs:
   * expressGlobalTag: 124X_dataRun3_Express_Candidate_2022_06_16_09_23_11
   * promptrecoGlobalTag: 124X_dataRun3_Prompt_Candidate_2022_06_16_09_23_34
   * alcap0GlobalTag: 124X_dataRun3_Prompt_Candidate_2022_06_16_09_23_34
* Additional changes:

**Purpose of the test**  
Early identification of issues with 12_4_X releases

**T0 Operations cmsTalk thread**  No post yet
[Tier0 Operations cmsTalk Forum](https://cms-talk.web.cern.ch/c/offcomp/compops/tier0/210?)

### CODE REVIEW

**Comment by francescobrivio** [comment]
@germanfgv thankss for creating this! 
should we test also a cosmic run?

**Comment by germanfgv** [comment]
I can add it later

**Comment by francescobrivio** [comment]
@germanfgv what is the status of this replay (beside the issue with the Stream ScoutingPF reported in https://cms-talk.web.cern.ch/t/changes-to-stream-scoutingpf-in-cmssw-12-4-0/11790)?

**Comment by tvami** [comment]
hi @germanfgv 
I understand this finished, and anyway we'll have 12_4_1 in a few days. Can you please close this PR?

**Pull request closed without merging**
