### PR TITLE
Production configuration for Run3 May collisions

### PR DESCRIPTION
**Pull request by germanfgv**
Production configuration following results in #4677

### CODE REVIEW

**Comment by germanfgv** [comment]
fyi @francescobrivio

**Comment by francescobrivio** [comment]
@germanfgv I spotted these differences:

- for the dataset `DoubleEG` you forgot to update one of the producers from `HcalCalIsoTrkFilter` to `HcalCalIsoTrkProducerFilter`
- for the datasets `AlCaLumiPixelsCountsPrompt*` there are few flags that should be switched to true:
  - `do_reco = True`
  - `write_reco = True`
  - `write_aod = True`
  - and add `disk_node="T2_CH_CERN"`

**Comment by germanfgv** [comment]
test syntax please

**Comment by francescobrivio** [comment]
+1 on commit [37bd26c](https://github.com/dmwm/T0/pull/4678/commits/37bd26cef9a68fdeb2716a55c5849aa86b6373c4)

**Comment by tvami** [comment]
Although it's not for collisions, I think we should add the cosmics producer `SiStripCalCosmicsNano`, it was tested and works https://github.com/dmwm/T0/pull/4661 -- just so that we dont forget about this

**Comment by jhonatanamado** [comment]
Hi @germanfgv . German please take into account the following changes that were included in  https://github.com/dmwm/T0/pull/4668 , https://github.com/jhonatanamado/T0/blob/0a24d7c7243def7f24edeb8f3a6afe15cf1b3d12/etc/ProdOfflineConfiguration.py#L961-L975
```
DATASETS = ["AlCaLumiPixelsCountsExpress0", "AlCaLumiPixelsCountsExpress1", "AlCaLumiPixelsCountsExpress2", "AlCaLumiPixelsCountsExpress3",
            "AlCaLumiPixelsCountsExpress4", "AlCaLumiPixelsCountsExpress5", "AlCaLumiPixelsCountsExpress6", "AlCaLumiPixelsCountsExpress7",
            "AlCaLumiPixelsCountsExpress8", "AlCaLumiPixelsCountsExpress9", "AlCaLumiPixelsCountsExpress10", "AlCaLumiPixelsCountsExpress11",
            "AlCaLumiPixelsCountsExpress12", "AlCaLumiPixelsCountsExpress"]

for dataset in DATASETS:
    addDataset(tier0Config, dataset,
               do_reco=True,
               write_reco=False, write_aod=False, write_miniaod=False, write_dqm=False,
               reco_split=alcarawSplitting,
               proc_version=alcarawProcVersion,
               alca_producers=["AlCaPCCZeroBias", "RawPCCProducer"],
               timePerEvent=0.02,
               sizePerEvent=38,
               scenario=alcaLumiPixelsScenario)
```
If Im not wrong, this will allow promptreco for the PD `AlCaLumiPixelsCountsExpressX` due that the rate for that stream will be splitted. FYI @tvami

**Pull request merged**
