### PR TITLE
Replay test with CMSSW_11_3_2

### PR DESCRIPTION
**Pull request by qliphy**
Test of CMSSW_11_3_2 for the CRUZET (July 12 - Aug 14).

Runs include 341169, 341754, 338628, 338714, 342154. 

The GTs are: 
 HLT    : 113X_dataRun3_HLT_Candidate_2021_07_02_14_05_25
 Express: 113X_dataRun3_Express_Candidate_2021_07_02_14_38_40
 Prompt : 113X_dataRun3_Prompt_v3

### CODE REVIEW

**Comment by qliphy** [comment]
11_3_2 has been made:  https://github.com/cms-sw/cmssw/releases/CMSSW_11_3_2
However, for some reason, it doesn't appear yet in /cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/

To trigger the test a bit later.  In the meantime, @germanfgv  let me know if you have any comment on the settings.

**Comment by qliphy** [comment]
run replay please

**Comment by silviodonato** [comment]
cc @perrotta

**Comment by germanfgv** [comment]
> 11_3_2 has been made: https://github.com/cms-sw/cmssw/releases/CMSSW_11_3_2
> However, for some reason, it doesn't appear yet in /cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/
> 
> To trigger the test a bit later.
> 
> In the meantime, @germanfgv let me know if you have any comment on the settings.

I added overrides for release 11_3_1 in express and repack, and then stopped the replay. I'll start it again.

**Comment by germanfgv** [comment]
run replay please

**Comment by germanfgv** [comment]
@qliphy the paused jobs reffered to in the bot's comments are all NanoDST memory issues that will not be present during CRUZET as we alredy have a fix to assign more memory to them. The replays is running without problems so far.

**Comment by germanfgv** [comment]
@qliphy The paused jobs that appear on this report are due to a problem reading files from EOS. 
We are trying to understand what caused this problem. In the meantime, we launched another replay with the same configuration, It is still running, and we have no issues so far. the paused jobs from the previous replay have already finished successfully

**Comment by germanfgv** [comment]
@qliphy as I mentioned in HN (https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/2238/1.html) the replay finished without issues

**Comment by qliphy** [comment]
> @qliphy as I mentioned in HN (https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/2238/1.html) the replay finished without issues

Great! thanks a lot.

**Comment by mmusich** [comment]
I see that in the tested configuration the alcas are not the one at https://twiki.cern.ch/twiki/bin/view/CMS/AlCaRecoMatrix#Cosmic_RUn_at_ZEro_Tesla_CRU_AN1.
In particular, we have requested that this 
https://github.com/dmwm/T0/blob/70e085df6521685933e06fe92b85d0134277565d/etc/ReplayOfflineConfiguration.py#L428-L441

should contain:

```python
                alca_producers=["TkAlCosmics0T", "MuAlGlobalCosmics", "SiStripCalCosmics", "SiPixelCalCosmics"], 
```

@tvami @francescobrivio @tocheng

**Comment by francescobrivio** [comment]
> I see that in the tested configuration the alcas are not the one at https://twiki.cern.ch/twiki/bin/view/CMS/AlCaRecoMatrix#Cosmic_RUn_at_ZEro_Tesla_CRU_AN1.
> In particular, we have requested that this
> 
> https://github.com/dmwm/T0/blob/70e085df6521685933e06fe92b85d0134277565d/etc/ReplayOfflineConfiguration.py#L428-L441
> 
> should contain:
> 
> ```python
>                 alca_producers=["TkAlCosmics0T", "MuAlGlobalCosmics", "SiStripCalCosmics", "SiPixelCalCosmics"], 
> ```
> 
> @tvami @francescobrivio @tocheng

You are right @mmusich , actually the line should be: 
```python
alca_producers=["TkAlCosmics0T", "MuAlGlobalCosmics", "SiStripCalCosmics", "SiPixelCalCosmics", "DtCalibCosmics"], 
```
I'm sorry we didn't spot this in the configuration before the replay was started.

**Comment by germanfgv** [comment]
So it is not a subset as stated during today's meeting. If that's the case, I'll repeat the test changing the configuration and let you know the results.

> I see that in the tested configuration the alcas are not the one at https://twiki.cern.ch/twiki/bin/view/CMS/AlCaRecoMatrix#Cosmic_RUn_at_ZEro_Tesla_CRU_AN1.
> In particular, we have requested that this
> https://github.com/dmwm/T0/blob/70e085df6521685933e06fe92b85d0134277565d/etc/ReplayOfflineConfiguration.py#L428-L441
> 
> should contain:
> 
> ```python
>                 alca_producers=["TkAlCosmics0T", "MuAlGlobalCosmics", "SiStripCalCosmics", "SiPixelCalCosmics"], 
> ```
> 
> @tvami @francescobrivio @tocheng

**Comment by francescobrivio** [comment]
> So it is not a subset as stated during today's meeting. If that's the case, I'll repeat the test changing the configuration and let you know the results.
> 

Hi @germanfgv yes I'm sorry I was wrong during the meeting: we had only checked the Express configuration and not the Prompt one, our mistake. The express and prompt matrix at https://twiki.cern.ch/twiki/bin/view/CMS/AlCaRecoMatrix#Cosmic_RUn_at_ZEro_Tesla_CRU_AN1 should now be up to date.

**Comment by germanfgv** [comment]
@francescobrivio I think it should actually be:
```
alca_producers=["TkAlCosmics0T", "MuAlGlobalCosmics", "SiStripCalCosmics", "SiPixelCalCosmics", "DtCalibCosmics","HcalCalIterativePhiSym"], 
```
 Am I wrong?

> You are right @mmusich , actually the line should be:
> 
> ```python
> alca_producers=["TkAlCosmics0T", "MuAlGlobalCosmics", "SiStripCalCosmics", "SiPixelCalCosmics", "DtCalibCosmics"], 
> ```
> 
> I'm sorry we didn't spot this in the configuration before the replay was started.

**Comment by francescobrivio** [comment]
> @francescobrivio I think it should actually be:
> 
> ```
> alca_producers=["TkAlCosmics0T", "MuAlGlobalCosmics", "SiStripCalCosmics", "SiPixelCalCosmics", "DtCalibCosmics","HcalCalIterativePhiSym"], 
> ```
> 
> Am I wrong?
> 

Actually HCal experts confirmed that `"HcalCalIterativePhiSym"` can and should be removed from the list.

**Comment by francescobrivio** [comment]
@germanfgv are you going also to use the Express versioned GT (113X_dataRun3_Express_v4) ?
It is effectively identical to the Candidate (https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun3_Express_Candidate_2021_07_02_14_38_40/113X_dataRun3_Express_v4), so one or the other does not really change...

**Comment by germanfgv** [comment]
@francescobrivio All PromptReco Cosmics jobs failed with the following error
```
Step: ALCAPRODUCER Spec: ['TkAlCosmics0T', 'MuAlGlobalCosmics', 'SiStripCalCosmics', 'SiPixelCalCosmics', 'DtCalibCosmics']
The following alcas could not be found ['DtCalibCosmics']
available  ['EcalESAlign', 'LumiPixels', 'PromptCalibProdSiStripGainsAAG', 'SiPixelCalZeroBias', 'PromptCalibProdEcalPedestals', 'TkAlMuonIsolatedPA', 'TkAlUpsilonMuMu', 'EcalCalEtaCalib', 'HcalCalIsolatedBunchSelector', 'HcalCalHBHEMuonFilter', 'EcalUncalZElectron', 'MuAlGlobalCosmics', 'MuAlZMuMu', 'TkAlBeamHalo', 'HcalCalIsoTrk', 'AlCaPCCZeroBias', 'PromptCalibProdLumiPCC', 'MuAlGlobalCosmicsInCollisions', 'TkAlCosmicsInCollisions', 'RawPCCProducer', 'MuAlOverlaps', 'TkAlMinBias', 'EcalTestPulsesRaw', 'MuAlBeamHaloOverlaps', 'Hotline', 'TkAlCosmics0T', 'EcalUncalWElectron', 'PromptCalibProdSiPixel', 'PromptCalibProd', 'SiPixelCalSingleMuon', 'SiStripCalMinBiasAAG', 'SiStripCalZeroBias', 'TkAlMuonIsolated', 'PromptCalibProdBeamSpotHP', 'PromptCalibProdSiStrip', 'TkAlCosmics0THLT', 'PromptCalibProdSiPixelAli', 'TkAlUpsilonMuMuPA', 'EcalCalWElectron', 'TkAlLAS', 'TkAlZMuMu', 'AlCaPCCZeroBiasFromRECO', 'EcalTrg', 'TkAlJpsiMuMu', 'RpcCalHLT', 'SiStripCalCosmics', 'AlCaPCCRandom', 'SiStripPCLHistos', 'HcalCalPedestal', 'SiStripCalSmallBiasScan', 'HcalCalIterativePhiSym', 'TkAlCosmics', 'TkAlZMuMuPA', 'SiPixelCalCosmics', 'HcalCalDijets', 'PromptCalibProdSiStripGains', 'AlCaPCCRandomFromRECO', 'PromptCalibProdBeamSpotHPLowPU', 'EcalCalPi0Calib', 'HcalCalLowPUHBHEMuonFilter', 'LumiPixelsMinBias', 'HcalCalGammaJet', 'EcalCalZElectron', 'HcalCalIsolatedBunchFilter', 'TkAlCosmicsHLT', 'HcalCalIsoTrkFilter', 'HcalCalNoise', 'HcalCalHOCosmics', 'MuAlCalIsolatedMu', 'SiStripCalMinBias', 'MuAlBeamHalo', 'HcalCalHO', 'HcalCalMinBias', 'HcalCalHEMuonFilter']
2021-07-09 23:09:40,978:ERROR:SetupCMSSWPset:Failed to load process from Scenario cosmicsEra_Run3 (<Configuration.DataProcessing.Impl.cosmicsEra_Run3.cosmicsEra_Run3 object at 0x2ae5caa3f7d0>).
2021-07-09 23:09:40,978:ERROR:SetupCMSSWPset:Error creating process for Config/DataProcessing:
Traceback (most recent call last):
  File "/build/dmwmbld/srv/state/dmwmbld/builds/comp_gcc630/w/BUILD/slc7_amd64_gcc630/cms/t0/2.2.4/cms+t0+2.2.4-1/WMCore_t0/build/lib/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py", line 718, in __call__
    self.createProcess(scenario, funcName, funcArgs)
  File "/build/dmwmbld/srv/state/dmwmbld/builds/comp_gcc630/w/BUILD/slc7_amd64_gcc630/cms/t0/2.2.4/cms+t0+2.2.4-1/WMCore_t0/build/lib/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py", line 236, in createProcess
    raise ex
Exception: The following alcas could not be found ['DtCalibCosmics']
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc900/external/python/2.7.15-bcolbf2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc900/external/python/2.7.15-bcolbf2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/build/dmwmbld/srv/state/dmwmbld/builds/comp_gcc630/w/BUILD/slc7_amd64_gcc630/cms/t0/2.2.4/cms+t0+2.2.4-1/WMCore_t0/build/lib/WMCore/WMRuntime/ScriptInvoke.py", line 118, in <module>
RuntimeError: Error invoking script for step WMTaskSpace.cmsRun1
withe Script module: SetupCMSSWPset
The following alcas could not be found ['DtCalibCosmics']Details:
  File "/build/dmwmbld/srv/state/dmwmbld/builds/comp_gcc630/w/BUILD/slc7_amd64_gcc630/cms/t0/2.2.4/cms+t0+2.2.4-1/WMCore_t0/build/lib/WMCore/WMRuntime/ScriptInvoke.py", line 110, in <module>
  File "/build/dmwmbld/srv/state/dmwmbld/builds/comp_gcc630/w/BUILD/slc7_amd64_gcc630/cms/t0/2.2.4/cms+t0+2.2.4-1/WMCore_t0/build/lib/WMCore/WMRuntime/ScriptInvoke.py", line 81, in invoke
  File "/build/dmwmbld/srv/state/dmwmbld/builds/comp_gcc630/w/BUILD/slc7_amd64_gcc630/cms/t0/2.2.4/cms+t0+2.2.4-1/WMCore_t0/build/lib/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py", line 721, in __call__
    raise ex


        Stderr: None 
	ModuleName : None
	MethodName : __init__
	ClassInstance : None
	FileName : /build/dmwmbld/srv/state/dmwmbld/builds/comp_gcc630/w/BUILD/slc7_amd64_gcc630/cms/t0/2.2.4/cms+t0+2.2.4-1/WMCore_t0/build/lib/WMCore/WMSpec/Steps/WMExecutionFailure.py
	ClassName : None
	LineNumber : 18
	ErrorNr : 50513

Traceback: 

<@---------- WMException End ----------@>
```
It was not possible to use `DtCalibCosmics`. Given how late it its, I don't think we would be able to use this producer during CRUZET. I'll test again without that producer (ie, using @mmusich 's suggestion)

**Comment by mmusich** [comment]
@germanfgv @francescobrivio 
`DtCalibCosmics` has been removed from cmssw in PR https://github.com/cms-sw/cmssw/pull/30041 by @jfernan2, therefore it cannot be configured in the Tier-0 configuration. I am not sure why this is still proposed.

**Comment by germanfgv** [comment]
I'm running a replay  with @mmusich suggested producers.
> ```
> alca_producers=["TkAlCosmics0T", "MuAlGlobalCosmics", "SiStripCalCosmics", "SiPixelCalCosmics"], 
> ```
@francescobrivio could you please update the AlCa Reco matrix?

**Comment by francescobrivio** [comment]
Thanks @mmusich I was not aware `DtCalibCosmics` had been removed.
@germanfgv  I will update the matrix.

**Comment by germanfgv** [comment]
I'm closing this PR. This configuration was added to the master branch with #4587

**Pull request closed without merging**
