### PR TITLE
test 12_0_2_patch2

### PR DESCRIPTION
**Pull request by qliphy**
# Replay Request

**Requetor
ORP, T0 (@germanfgv @qliphy, @perrotta)

Following https://github.com/dmwm/T0/pull/4614 and #4621

**Describe the configuration**  
* Release: CMSSW_12_0_2_patch2
* Run: 343082,344063
* GTs:
   * expressGlobalTag: 120X_dataRun3_Express_v2
   * promptrecoGlobalTag: 120X_dataRun3_Prompt_v2
   * alcap0GlobalTag: 120X_dataRun3_Prompt_v2
* Additional changes:

**Purpose of the test**  
 T0 validation of CMSSW pre-releases for early detection of issues with T0 workflows

**T0 Operations HyperNews thread**   
https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/2285.html

### CODE REVIEW

**Comment by qliphy** [comment]
run replay please

**Comment by francescobrivio** [comment]
Hi @qliphy please use the production GTs for tje replay on cosmics data:
 -  expressGlobalTag: 120X_dataRun3_Express_v2
 -   promptrecoGlobalTag: 120X_dataRun3_Prompt_v2
 - alcap0GlobalTag: 120X_dataRun3_Prompt_v2

**Comment by germanfgv** [comment]
@qliphy please remember to create the HN thread as suggested in the PR template

**Comment by qliphy** [comment]
> @qliphy please remember to create the HN thread as suggested in the PR template

@germanfgv   Done.  https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/2285.html

**Pull request closed without merging**
