### PR TITLE
Replay to test CMSSW_13_0_7

### PR DESCRIPTION
**Pull request by LinaresToine**
# Replay Request

**Requestor**  
David Lange

**Describe the configuration**  
* Release: CMSSW_13_0_7
* Run: 367102
* GTs:
   * expressGlobalTag: 130X_dataRun3_Express_v2
   * promptrecoGlobalTag: 130X_dataRun3_Prompt_v3
* Additional changes:

**Purpose of the test**  

Test new CMSSW_13_0_7

**T0 Operations cmsTalk thread**  
https://cms-talk.web.cern.ch/t/replay-for-testing-cmssw-13-0-7/24675

### CODE REVIEW

**Comment by LinaresToine** [comment]
test syntax please

**Comment by francescobrivio** [comment]
@LinaresToine what is the status of this replay?
Cheers,
Francesco as this week's ORM

**Comment by davidlange6** [comment]
I had checked Friday, but didn’t post anything. It looked to me like all jobs finished successfully. Can discuss in the ops meeting if this is ready or still had problems.

Cheers-
David


From: francescobrivio ***@***.***>
Date: Monday, May 29, 2023 at 12:45 PM
To: dmwm/T0 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [dmwm/T0] Replay to test cmssw 13 0 7 (PR #4831)

@LinaresToine<https://github.com/LinaresToine> what is the status of this replay?
Cheers,
Francesco as this week's ORM

**Comment by LinaresToine** [comment]
Hello @francescobrivio and @davidlange6.

The replay was successful. The output files are [here](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2F*%2F*v26125202*%2F*).

**Comment by germanfgv** [comment]
Merging these changes in #4833

**Pull request closed without merging**
