### PR TITLE
Replay to test new Run-3 LumiPCC PCL wf

### PR DESCRIPTION
**Pull request by tvami**
# Replay Request

**Requestor**  

AlCaDB

**Describe the configuration**  
* Release: ~~CMSSW_12_3_0_pre6~~ then ~~CMSSW_12_4_0_pre2~~ then CMSSW_12_3_0
* Run: 346512 (2021 pp)
* GTs:
   * expressGlobalTag: 123X_dataRun3_Express_TIER0_REPLAY_Run2_v1
   * promptrecoGlobalTag: ~123X_dataRun3_Prompt_TIER0_REPLAY_Run2_v2~ then 123X_dataRun3_Prompt_TIER0_REPLAY_Run2_v3
   * alcap0GlobalTag: ~123X_dataRun3_Prompt_TIER0_REPLAY_Run2_v2~ 123X_dataRun3_Prompt_TIER0_REPLAY_Run2_v3
* Additional changes: Commented out old wf-s, added the new AlCa producers 

**Purpose of the test**  

To test new Run-3 LumiPCC PCL wf

https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_dataRun3_Prompt_TIER0_REPLAY_Run2_v2/123X_dataRun3_Prompt_TIER0_REPLAY_Run2_v3

Adding the tag from Prep DB produced by a prev replay to test prompt. 

**T0 Operations cmsTalk thread**  

https://cms-talk.web.cern.ch/t/replay-new-lumipcc-pcl-workflows-for-run-3/8060

### CODE REVIEW

**Comment by benitezj** [comment]
For the express stream, I'm only wondering where the harvest path is run: ALCAHARVEST:LumiPCC 
and also if the ALCARECO is saved from the express jobs.

**Comment by benitezj** [comment]
For the Prompt stream, I noticed you kept the 0-11 streams even  though we did not get those yet. But it could be good to keep for the future they may be needed.

**Comment by tvami** [comment]
> For the express stream, I'm only wondering where the harvest path is run: ALCAHARVEST:LumiPCC 

That's in the autoPCL, look here
https://github.com/cms-sw/cmssw/blob/master/Configuration/AlCa/python/autoPCL.py#L11
PromptCalibProdLumiPCC is the same as ALCAHARVEST:LumiPCC

> and also if the ALCARECO is saved from the express jobs.

Yes, to CERN T2: https://github.com/dmwm/T0/blob/1e5d3102a07819db9411685ef10333039ccd41bf/etc/ReplayOfflineConfiguration.py#L380

**Comment by benitezj** [comment]
ok. So lets proceed and check the output

**Comment by tvami** [comment]
run replay please

**Comment by tvami** [comment]
I understand from @jhonatanamado that the standard part of this replay finished w/o any issues. So we can consider pre6 to be validated.

Unfortunately for the new part introduced in this PR, i.e. the addition of the LumiPCC, didnt produce any outputs, so we'll have another replay which is just the LumiPCC and nothing else. We shall do this after the transfer tests finish tomorrow.

**Comment by gkfthddk** [comment]
> Monitoring for replay is closed. Log Begins ==== Tier0_REPLAY v432 DMWM-T0-PR-test-job on vocms047.cern.ch. Replay to test new Run-3 LumiPCC PCL wf JIRA URL : None _Return 8020: 6 job(s)_ Error message: INFO:root:CMSSW configured for GPU required: forbidden, with these settings: None INFO:root:Executing CMSSW step INFO:root:Runing SCRAM INFO:root:Running PRE scripts INFO:root: Invoking command: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH /cvmfs/cms.cern.ch/COMP/slc7_amd64_gcc630/external/python3/3.8.2-comp/bin/python3 -m WMCore.WMRuntime.ScriptInvoke WMTaskSpace.cmsRun1 SetupCMSSWPset
> 
> INFO:root:RUNNING SCRAM SCRIPTS INFO:root:Executing CMSSW. args: ['/bin/bash', '/srv/job/WMTaskSpace/cmsRun1/cmsRun1-main.sh', '', 'slc7_amd64_gcc10', 'scramv1', 'CMSSW', 'CMSSW_12_3_0_pre6', 'FrameworkJobReport.xml', 'cmsRun', 'PSet.py', '', '', ''] CRITICAL:root:Error running cmsRun {'arguments': ['/bin/bash', '/srv/job/WMTaskSpace/cmsRun1/cmsRun1-main.sh', '', 'slc7_amd64_gcc10', 'scramv1', 'CMSSW', 'CMSSW_12_3_0_pre6', 'FrameworkJobReport.xml', 'cmsRun', 'PSet.py', '', '', '']} CMSSW Return code: 8020
> 
> CRITICAL:root:Error message: An exception of category 'FileOpenError' occurred while [0] Constructing the EventProcessor [1] Constructing input source of type PoolSource [2] Calling RootInputFileSequence::initTheFile() [3] Calling StorageFactory::open() [4] Calling XrdFile::open() Exception Message: Failed to open the file 'root://eoscms.cern.ch//eos/cms/tier0/store/backfill/1/data/Tier0_REPLAY_2022/ZeroBias12/RAW/v213/000/346/512/00000/1d0aa086-a999-484d-a37d-5bb318141d93.root?eos.app=cmst0' Additional Info: [a] Input file root://eoscms.cern.ch//eos/cms/tier0/store/backfill/1/data/Tier0_REPLAY_2022/ZeroBias12/RAW/v213/000/346/512/00000/1d0aa086-a999-484d-a37d-5bb318141d93.root?eos.app=cmst0 could not be opened.
> 
> End Of Log ====

Monitoring is not closed yet.

**Comment by francescobrivio** [comment]
run replay please

 - after private conversation with @jhonatanamado

**Comment by jhonatanamado** [comment]
Hello folks, @francescobrivio @tvami this replay is about to finish but did not generate express workflows. This due that the run  346512 doesn't have a streamer called `AlcaLumiPixelsExpress`. Remember that express wfs run over streamer files. (Also check that the name must be the same as the argument given to the function Ex.
`addExpressConfig(tier0config, "streamerfile", ...)`)
The streamer files available for this run are the following:
```
ALCALumiPixelsCountsExpress/000/346/512/:
ALCALumiPixelsCountsPrompt/000/346/512/:
ALCAPHISYM/000/346/512/:
Calibration/000/346/512/:
Express/000/346/512/:
ExpressAlignment/000/346/512/:
HLTMonitor/000/346/512/:
NanoDST/000/346/512/:
Physics/000/346/512/:
PhysicsMinimumBias0/000/346/512/:
PhysicsMinimumBias1/000/346/512/:
PhysicsMinimumBias2/000/346/512/:
PhysicsMinimumBias3/000/346/512/:
PhysicsMinimumBias4/000/346/512/:
PhysicsMinimumBias5/000/346/512/:
PhysicsMinimumBias6/000/346/512/:
PhysicsMinimumBias7/000/346/512/:
PhysicsMinimumBias8/000/346/512/:
PhysicsMinimumBias9/000/346/512/:
PhysicsZeroBias0/000/346/512/:
PhysicsZeroBias10/000/346/512/:
PhysicsZeroBias1/000/346/512/:
PhysicsZeroBias11/000/346/512/:
PhysicsZeroBias12/000/346/512/:
PhysicsZeroBias13/000/346/512/:
PhysicsZeroBias14/000/346/512/:
PhysicsZeroBias15/000/346/512/:
PhysicsZeroBias16/000/346/512/:
PhysicsZeroBias17/000/346/512/:
PhysicsZeroBias18/000/346/512/:
PhysicsZeroBias19/000/346/512/:
PhysicsZeroBias2/000/346/512/:
PhysicsZeroBias3/000/346/512/:
PhysicsZeroBias4/000/346/512/:
PhysicsZeroBias5/000/346/512/:
PhysicsZeroBias6/000/346/512/:
PhysicsZeroBias7/000/346/512/:
PhysicsZeroBias8/000/346/512/:
PhysicsZeroBias9/000/346/512/:
```

**Comment by tvami** [comment]
Thanks @jhonatanamado it should be the `ALCALumiPixelsCountsExpress`, but I thought that's what we did in the original replay. I'm afraid we'll have to have a patch to CMSSW's autoAlca.py file.

**Comment by tvami** [comment]
Yes, `1e5d3102a07819db9411685ef10333039ccd41bf` had the AlCaLumiPixelCountsExpress

**Comment by tvami** [comment]
run replay please

**Comment by tvami** [comment]
run replay please

**Comment by davidlange6** [comment]
For my education, how will this replay differ from the previous one?

On Mar 30, 2022 8:54 PM, Tamas Vami ***@***.***> wrote:

run replay please

**Comment by tvami** [comment]
>For my education, how will this replay differ from the previous one?

If you are referring to this one:
https://github.com/dmwm/T0/pull/4650#issuecomment-1083250126
that didn't run, due to the fact that the pre2 was not yet present in `cvmfs`, and now it is

**Comment by davidlange6** [comment]
Ha. So much for "Replay was succesfull". Thanks

On Mar 30, 2022 9:35 PM, Tamas Vami ***@***.***> wrote:

For my education, how will this replay differ from the previous one?

If you are referring to this one:
#4650 (comment)<https://github.com/dmwm/T0/pull/4650#issuecomment-1083250126>
that didn't run, due to the fact that the pre2 was not yet present in cvmfs, and now it is

**Comment by tvami** [comment]
> Ha. So much for "Replay was succesfull". Thanks

Yeah that msg should be improved haha, @jhonatanamado this is because you manually killed the agent?

**Comment by jhonatanamado** [comment]
> > Ha. So much for "Replay was succesfull". Thanks
> 
> Yeah that msg should be improved haha, @jhonatanamado this is because you manually killed the agent?

Heheh Yes probably was due that I killed the agent and that replay didnt trigger jobs. We will improve that message,

**Comment by tvami** [comment]
Let me report this here, too
Here is the output of this replay
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset+dataset%3D%2F*%2F*v20220330*%2F*

It seems that `AlcaLumiPixelsExpress` didnt work, and so the `ALCALumiPixelsCountsPromptX` was not produced. We need the logs to understand what went wrong.

**Comment by jhonatanamado** [comment]
run replay please

**Comment by tvami** [comment]
Ok this finally finished nicely
The output files can be found here:
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset+dataset%3D%2F*%2F*Tier0_REPLAY_2022*-v11*%2F*

```
/AlCaLumiPixelsCountsPrompt/Tier0_REPLAY_2022-v11/RAW
/StreamALCALumiPixelsCountsExpress/Tier0_REPLAY_2022-AlCaPCCRandom-Express-v11/ALCARECO
/StreamALCALumiPixelsCountsExpress/Tier0_REPLAY_2022-Express-v11/DQMIO
/StreamALCALumiPixelsCountsExpress/Tier0_REPLAY_2022-PromptCalibProdLumiPCC-Express-v11/ALCAPROMPT
```

@benitezj please have a look at these files and report back if they are as expected. Thanks!

**Comment by tvami** [comment]
For the record 
This is the output tag for the replay:
https://cms-conddb.cern.ch/cmsDbBrowser/list/Prep/tags/LumiPCC_Corrections_prep_prompt

There was an upload on 
2022-04-01
with run 346512 which is the run number that we used for the replay. So this at least is promising. @benitezj will have a look at the content of the payload.

He also asked to look into the logs with the harvester for some further debugging.

**Comment by tvami** [comment]
run replay please

**Comment by tvami** [comment]
I've changed to the newly announced `CMSSW_12_3_0`
https://cms-talk.web.cern.ch/t/production-release-cmssw-12-3-0-now-available/9142/1
which now has the correct Run-3 era in the scenario for LumiPCC

**Comment by jhonatanamado** [comment]
run replay please

**Comment by germanfgv** [comment]
The replay was stuck because our DB does not include `AlCaLumiPixels_Run3` scenario yet. I added it manually and now the replay is moving forward. I also made a commit adding the necessary modifications to our code to include the scenario in the future.

**Comment by tvami** [comment]
run replay please

**Comment by tvami** [comment]
The replay finished, the output is here:
[https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset+dataset%3D%2F*%2F*Tier0_REPLAY_2022*-v17*%2F*](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset+dataset%3D%2F*%2F*Tier0_REPLAY_2022*-v17*%2F*)

**Comment by tvami** [comment]
I update the GT to `123X_dataRun3_Prompt_TIER0_REPLAY_Run2_v3`
https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/123X_dataRun3_Prompt_TIER0_REPLAY_Run2_v2/123X_dataRun3_Prompt_TIER0_REPLAY_Run2_v3

Adding the tag from Prep DB produced by a prev replay to test prompt reco.

**Comment by tvami** [comment]
The outcome of the latest replay
```
/AlCaLumiPixelsCountsPrompt/Tier0_REPLAY_2022-AlCaPCCZeroBias-PromptReco-v19/ALCARECO/AlCaLumiPixelsCountsPrompt/Tier0_REPLAY_2022-v19/RAW/StreamALCALumiPixelsCountsExpress/Tier0_REPLAY_2022-Express-v19/DQMIO/StreamALCALumiPixelsCountsExpress/Tier0_REPLAY_2022-AlCaPCCRandom-Express-v19/ALCARECO/AlCaLumiPixelsCountsPrompt/Tier0_REPLAY_2022-RawPCCProducer-PromptReco-v19/ALCARECO/StreamALCALumiPixelsCountsExpress/Tier0_REPLAY_2022-PromptCalibProdLumiPCC-Express-v19/ALCAPROMPT
```

**Comment by tvami** [comment]
Lumi group reported that the lastest results are according to the expectation, so we can consider this replay successful! I'm closing the PR now

**Pull request closed without merging**
