### PR TITLE
Add AlCaLumiPixelsCountsUngated dataset for VdM scans

### PR DESCRIPTION
**Pull request by francescobrivio**
**Requestor**  
Francesco Brivio for the LumiPOG

**Describe the configuration**  
* Release: unchanged from current prod
* Run: unchanged from current prod
* GTs:
   * expressGlobalTag: unchanged from current prod
   * promptrecoGlobalTag: unchanged from current prod
   * alcap0GlobalTag: unchanged from current prod
* Additional changes:
   * Added `AlCaLumiPixelsCountsUngated` dataset that will be produced during the upcoming VdM scans
      * Only RAW output will be produced

**Purpose of the test**  
This PR is intended to add the configuration for the `AlCaLumiPixelsCountsUngated` that will be produced during the upcoming VdM scans. No alca-producers or skims are added as only the RAW output dataset is expected.
This is a new dataset so there is no run to be used for a possible replay.
More details can be found in https://its.cern.ch/jira/browse/CMSHLT-2460.

**T0 Operations cmsTalk thread**  
https://cms-talk.web.cern.ch/t/add-configuration-for-alcalumipixelscountsungated-dataset/15328

### CODE REVIEW

**Comment by francescobrivio** [comment]
test syntax please

**Comment by germanfgv** [comment]
Thanks for the PR @francescobrivio. Everythings seems to be in order.  Adding this to the configuration won't have any effects on T0, as we repack everything by default. I do think is good to have the PD in our config, if anything, just to acknowledge it is there.

I do have a question. Right now, this raw files will not be stored in disk, just in tape. Maybe this data is needed in T2 Disk?

**Comment by francescobrivio** [comment]
> I do have a question. Right now, this raw files will not be stored in disk, just in tape. Maybe this data is needed in T2 Disk?

Hi @germanfgv sorry for the delay in answering: I don't know what the LumiPOG needs exactly, so I think it's better to ask this question on the [CMSTalk thread](https://cms-talk.web.cern.ch/t/add-configuration-for-alcalumipixelscountsungated-dataset/15328).

**Comment by germanfgv** [comment]
I'll merge this. We can add a disk copy later if necessary.

**Comment by tvami** [comment]
> I asked Gabi directly on the HLT JIRA where this was brought up, I hope she responds soon.

@germanfgv they need it on DISK

**Pull request merged**
