### PR TITLE
Delete blocks t0

### PR DESCRIPTION
**Pull request by germanfgv**
Test deleteBlocks from RucioInjector with T0 agent

### CODE REVIEW

**Comment by germanfgv** [comment]
run replay test

**Comment by germanfgv** [comment]
run replay please

**Comment by gkfthddk** [comment]
Host name : vocms047.cern.ch
Container ID : 1
Pull request url : https://github.com/dmwm/T0/pull/4547
Current build at jenkins : https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-T0-PR-test-job/205/.
Jira Issue : https://its.cern.ch/jira/browse/CMSTZDEV-616

**Comment by gkfthddk** [comment]
There are 1 paused jobs in the replay.

**Comment by gkfthddk** [comment]
There are 2 paused jobs in the replay.

**Comment by germanfgv** [comment]
run replay please

**Comment by gkfthddk** [comment]
Host name : vocms047.cern.ch
Container ID : 2
Pull request url : https://github.com/dmwm/T0/pull/4547
Current build at jenkins : https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-T0-PR-test-job/206/.
Jira Issue : https://its.cern.ch/jira/browse/CMSTZDEV-617

**Comment by germanfgv** [comment]
run replay please

**Comment by gkfthddk** [comment]
Host name : vocms047.cern.ch
Container ID : 1
Pull request url : https://github.com/dmwm/T0/pull/4547
Current build at jenkins : https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-T0-PR-test-job/207/.
Jira Issue : https://its.cern.ch/jira/browse/CMSTZDEV-618

**Comment by gkfthddk** [comment]
There are 2 paused jobs in the replay.

**Comment by gkfthddk** [comment]
Host name : vocms047.cern.ch
Container ID : 2
Pull request url : https://github.com/dmwm/T0/pull/4547
Current build at jenkins : https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-T0-PR-test-job/208/.
Jira Issue : https://its.cern.ch/jira/browse/CMSTZDEV-619

**Comment by gkfthddk** [comment]
There are 2 paused jobs in the replay.

**Comment by gkfthddk** [comment]
There are 3 paused jobs in the replay.

**Comment by germanfgv** [comment]
run replay please

**Comment by gkfthddk** [comment]
Host name : vocms047.cern.ch
Container ID : 2
Pull request url : https://github.com/dmwm/T0/pull/4547
Current build at jenkins : https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-T0-PR-test-job/209/.
Jira Issue : https://its.cern.ch/jira/browse/CMSTZDEV-620

**Comment by gkfthddk** [comment]
There are 2 paused jobs in the replay.

**Comment by gkfthddk** [comment]
There are 3 paused jobs in the replay.

**Comment by gkfthddk** [comment]
Host name : vocms047.cern.ch
Container ID : 4
Pull request url : https://github.com/dmwm/T0/pull/4547
Current build at jenkins : https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-T0-PR-test-job/211/.
Jira Issue : https://its.cern.ch/jira/browse/CMSTZDEV-621

**Comment by gkfthddk** [comment]
There are 1 paused jobs in the replay.

**Comment by gkfthddk** [comment]
There are 2 paused jobs in the replay.

**Comment by gkfthddk** [comment]
There are 2 paused jobs in the replay.

**Comment by gkfthddk** [comment]
There are 2 paused jobs in the replay.

**Comment by germanfgv** [comment]
run replay please

**Comment by gkfthddk** [comment]
Host name : vocms047.cern.ch
Container ID : 1
Pull request url : https://github.com/dmwm/T0/pull/4547
Current build at jenkins : https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-T0-PR-test-job/213/.
Jira Issue : https://its.cern.ch/jira/browse/CMSTZDEV-622

**Comment by germanfgv** [comment]
run replay please

**Comment by gkfthddk** [comment]
Host name : vocms047.cern.ch
Container ID : 3
Pull request url : https://github.com/dmwm/T0/pull/4547
Current build at jenkins : https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-T0-PR-test-job/214/.
Jira Issue : https://its.cern.ch/jira/browse/CMSTZDEV-623

**Pull request closed without merging**
