### PR TITLE
Replay testing CMSSW_12_4_9

### PR DESCRIPTION
**Pull request by germanfgv**
# Replay Request

**Requestor**  
ORM

**Describe the configuration**  
* Release: CMSSW_12_4_9
* Run: [356824](https://cmsoms.cern.ch/cms/runs/report?cms_run=356824)
* GTs:
   * expressGlobalTag: 124X_dataRun3_Express_v5
   * promptrecoGlobalTag: 124X_dataRun3_Prompt_v4
   * alcap0GlobalTag: 124X_dataRun3_Prompt_v4
* Additional changes:

**Purpose of the test**  
Test release to be used in Run2022E

**T0 Operations cmsTalk thread**  
https://cms-talk.web.cern.ch/t/replay-to-test-cmssw-12-4-9/15168

### CODE REVIEW

**Comment by francescobrivio** [comment]
@germanfgv there is also another development which needs to be included - see [this commit](https://github.com/francescobrivio/T0/commit/0eb3751a2d9c879c7f735b0e93e2ff5c87279a48)

**Comment by francescobrivio** [comment]
BTW GTs are fine!

**Comment by germanfgv** [comment]
The replay has started. It can be monitored  here:
https://monit-grafana.cern.ch/d/t_jr45h7k/cms-tier0-replayid-monitoring?orgId=11&var-Bin=5m&var-ReplayID=220919123816&var-JobType=All&var-WorkflowType=All&refresh=5s

**Comment by germanfgv** [comment]
The replay finished successfully.

**Comment by germanfgv** [comment]
This will be merged using #4754

**Pull request closed without merging**
