### PR TITLE
Replay Request CMSSW 12 3 5

### PR DESCRIPTION
**Pull request by amarini**
# Replay Request

**Requestor**  
Team or person that requests this replay

**Describe the configuration**  
* Release: CMSSW_12_3_5
* Run: 353689 (collisions)
* GTs:
       * expressGlobalTag: 123X_dataRun3_Express_v8
       *  promptrecoGlobalTag: 123X_dataRun3_Prompt_v10
       *  alcap0GlobalTag: 123X_dataRun3_Prompt_v10
* Additional changes:

**Purpose of the test**  
Full replay testing CMSSW_12_3_5, to assess if _patch1 introduced the problem in processing PPS FEDs.

**T0 Operations cmsTalk thread**  
[If necessary, provide a link to the cmsTalk thread announcing the test to the relevant groups. 
[Tier0 Operations cmsTalk Forum](https://cms-talk.web.cern.ch/c/offcomp/compops/tier0/210?)](https://cms-talk.web.cern.ch/t/protonreconstructionalgorithm-error-in-express-for-run-353689/11586/12)

### CODE REVIEW

**Comment by francescobrivio** [comment]
test syntax please

**Comment by germanfgv** [comment]
It seems we are having a problem contacting condor from our replay containers. I'll run the replay manually.

**Comment by germanfgv** [comment]
You can monitor the replay here:
https://monit-grafana.cern.ch/d/t_jr45h7k/cms-tier0-replayid-monitoring?orgId=11&var-Bin=5m&var-
ReplayID=220609224455&var-JobType=All&var-WorkflowType=All&from=now-12h&to=now&refresh=10s

**Comment by germanfgv** [comment]
We've got the same error messages from the replay. So I think this confirms that the patch didn't caused the problem.
```
cmsRun1
Fatal Exception (Exit Code: 8001)
An exception of category 'ProtonReconstructionAlgorithm' occurred while
   [0] Processing  Event run: 353689 lumi: 38 event: 23402264 stream: 7
   [1] Running path 'dqmoffline_step'
   [2] Prefetching for module CTPPSCommonDQMSource/'ctppsCommonDQMSourceOffline'
   [3] Calling method for module CTPPSProtonProducer/'ctppsProtons'
Exception Message:
Optics data not available for RP 2007498752, i.e. subDet=3 arm=1 station=2 rp=5.
```

**Comment by tvami** [comment]
Thanks @germanfgv , let's close this PR and free up the node then

**Pull request closed without merging**
