### PR TITLE
Initial replay configuration for MWGR4 2020

### PR DESCRIPTION
**Pull request by germanfgv**
First configuration test for MWGR#4:

Release: CMSSW_11_1_4
RUNS: 337240 and 337234
GT (**):
  + HLT: 111X_dataRun3_HLT_v2
  + Express: 111X_dataRun3_Express_v2
  + Prompt: 111X_dataRun3_Prompt_v2

### CODE REVIEW

**Comment by germanfgv** [comment]
test replay please

**Comment by germanfgv** [comment]
run replay please

**Comment by gkfthddk** [comment]
Host name : vocms047.cern.ch
Container ID : 3
Pull request url : https://github.com/dmwm/T0/pull/4542
Current build at jenkins : https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-T0-PR-test-job/198/.
Jira Issue : https://its.cern.ch/jira/browse/CMSTZDEV-611

**Comment by gkfthddk** [comment]
There are 1 paused jobs in the replay.

**Comment by gkfthddk** [comment]
There are 1 paused jobs in the replay.

**Comment by germanfgv** [comment]
run replay please

**Comment by gkfthddk** [comment]
Host name : vocms047.cern.ch
Container ID : 1
Pull request url : https://github.com/dmwm/T0/pull/4542
Current build at jenkins : https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-T0-PR-test-job/203/.
Jira Issue : https://its.cern.ch/jira/browse/CMSTZDEV-614

**Comment by gkfthddk** [comment]
There are 1 paused jobs in the replay.

**Comment by gkfthddk** [comment]
There are 2 paused jobs in the replay.

**Pull request merged**
