### PR TITLE
Adding PPS to DQM for all datasets

### PR DESCRIPTION
**Pull request by fabferro**
Adding ctpps to DQM for all datasets

### CODE REVIEW

**Comment by germanfgv** [comment]
@fabferro Can you provide some context for this PR? Are you interested in running a replay to test this sequence on ZeroBias workflows? which runs would you like to test?

**Comment by fabferro** [comment]
> 
> 
> @fabferro Can you provide some context for this PR? Are you interested in running a replay to test this sequence on ZeroBias workflows? which runs would you like to test?

We're including ctpps where it should be. A replay of ZeroBias of run (say) 322022 would be a good test. Do you think you can run the replay? Thanks!

**Comment by fabferro** [comment]
Ping

**Comment by germanfgv** [comment]
Hi @fabferro. I tried adding this changes with run 314473.
ZeroBias PromptReco jobs fail with the following error:
```
cmsRun1
Fatal Exception (Exit Code: 8001)
An exception of category 'CTPPSGeometry' occurred while
   [0] Processing global begin Run run: 314473
   [1] Calling method for module CTPPSDiamondDQMSource/'ctppsDiamondDQMSource'
Exception Message:
Not found detector with ID 2054160384, i.e. subDet=5 arm=0 station=1 rp=6
```

**Comment by fabferro** [comment]
I now realize there probably is a problem with a missing tag in the Prompt GT. Sorry. We might hold the PR until the issue is solved by AlCa/DB.

**Comment by tvami** [comment]
Looking at this line
https://github.com/dmwm/T0/blob/90be282da17e3df4a11c2cafa862886fba30df81/etc/ProdOfflineConfiguration.py#L122
the GT
https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/113X_dataRun3_Prompt_v3
is used contains the tag
`GeometryFileRcd | CTPPS | XMLFILE_CTPPS_Geometry_hlt | 314276 |  `

In the ReRECO GT we used `XMLFILE_CTPPS_Geometry_v1`, is this the desired geometry tag? If yes, I can created a Candidate GT which includes this tag.

But may I ask @fabferro why are we trying to include this in the 11_3_X CMSSW? 12_0_0 is out, and 12_0_X will be used for data taking in CRAFT/beam tests. The development branch right now is also 12_1_X. My understanding is that PPS installation will be done even after that, so minimally I'd say the replay should happen in 12_0_0 (or 12_1_0_pre3 if T0 accepts pre-releases [IIUC T0 prefers not to])

**Comment by malbouis** [comment]
Hi, I could run things successfully locally using this candidate instead of the Prompt tag:  [https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun3_Prompt_Candidate_2021_09_10_23_04_14/113X_dataRun3_Prompt_v3](https://cms-conddb.cern.ch/cmsDbBrowser/diff/Prod/gts/113X_dataRun3_Prompt_Candidate_2021_09_10_23_04_14/113X_dataRun3_Prompt_v3). It uses XMLFILE_CTPPS_Geometry_2021_113YV1 instead.
@fabferro, maybe it is worth running the replay with this GT Candidate instead and if it completes successfully we can update the Prompt tag.

**Comment by malbouis** [comment]
> But may I ask @fabferro why are we trying to include this in the 11_3_X CMSSW? 12_0_0 is out, and 12_0_X will be used for data taking in CRAFT/beam tests. The development branch right now is also 12_1_X. My understanding is that PPS installation will be done even after that, so minimally I'd say the replay should happen in 12_0_0 (or 12_1_0_pre3 if T0 accepts pre-releases [IIUC T0 prefers not to])

I agree with you @tvami!
So @fabferro , maybe the best thing to do here is to trigger another replay in the 12_0_0 with the appropriate Geometry tag.

**Comment by fabferro** [comment]
> 
> 
> > But may I ask @fabferro why are we trying to include this in the 11_3_X CMSSW? 12_0_0 is out, and 12_0_X will be used for data taking in CRAFT/beam tests. The development branch right now is also 12_1_X. My understanding is that PPS installation will be done even after that, so minimally I'd say the replay should happen in 12_0_0 (or 12_1_0_pre3 if T0 accepts pre-releases [IIUC T0 prefers not to])
> 
> I agree with you @tvami!
> So @fabferro , maybe the best thing to do here is to trigger another replay in the 12_0_0 with the appropriate Geometry tag include in the Prompt GT.

Yes, I agree. You may use the one you see working.

**Comment by francescobrivio** [comment]
This has finally been implemented in #4655, @fabferro please cose this PR.

**Pull request closed without merging**
