### PR TITLE
Test CMSSW_12_2_0

### PR DESCRIPTION
**Pull request by jhonatanamado**
# Replay Request

**Requestor**  
Team or person that requests this replay

**Describe the configuration**  
* Release: CMSSW_12_2_0
* Run: 345755, 346062, 346512, 347028
* GTs:
   * expressGlobalTag: 120X_dataRun3_Express_v2
   * promptrecoGlobalTag: 120X_dataRun3_Prompt_v2
   * alcap0GlobalTag:120X_dataRun3_Prompt_v2
* Additional changes:
None
**Purpose of the test**  
Test CMSS2_12_2_0 with runs the [345755, 346062, 346512] and 347028 (run with some issues in maxPSS)

**T0 Operations HyperNews thread**  
If necessary, provide a link to the HN thread announcing the test to the relevant groups. 
[Tier0 Operations HN Forum](https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/2328.html)

### CODE REVIEW

**Comment by jhonatanamado** [comment]
run replay please

**Comment by tvami** [comment]
I'm wondering if it would be helpful to do this test with the 12_2_X online GTs?

**Comment by jhonatanamado** [comment]
Hi @tvami. Im preparing the report, tarballs and logs for the jobs that are having issues. But we could try a small replay with the streamers affected with those tags and see how it goes.

**Comment by jhonatanamado** [comment]
run replay please

**Comment by jhonatanamado** [comment]
run replay please

**Comment by jhonatanamado** [comment]
run replay please

**Comment by jhonatanamado** [comment]
run replay please

**Comment by jhonatanamado** [comment]
run replay please

**Comment by gkfthddk** [comment]
run replay please - triggering test

**Comment by tvami** [comment]
I think this PR should be closed, 12_2_0 is known to have a problem, which was fixed in https://github.com/cms-sw/cmssw/pull/36779 so we just simple just move to 12_2_0_patch1 for testing. Btw 12_2_1 is about to come out so maybe it would make sense to wait for that?

**Pull request closed without merging**
