### PR TITLE
CMSSW_13_0_7_patch1 replay with new GTs

### PR DESCRIPTION
**Pull request by LinaresToine**
# Replay Request

**Requestor**  
ORM @sarafiorendi 

**Describe the configuration**  
* Release: CMSSW_13_0_7_patch1
* Run: 368389
* GTs: 
   * Exxpress global tag: 130X_dataRun3_Express_v3
   * Prompt global tag: 130X_dataRun3_Prompt_v4

### CODE REVIEW

**Comment by LinaresToine** [comment]
test syntax please

**Comment by LinaresToine** [comment]
run replay please

**Comment by LinaresToine** [comment]
Replay for run 368389 was successful. The output data is found in [this link](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2F*%2F*v8175054*%2F*)

**Comment by germanfgv** [comment]
Merging this in #4844

**Pull request closed without merging**
