### PR TITLE
Test CMSSW_12_2_0_pre3

### PR DESCRIPTION
**Pull request by jhonatanamado**
# Replay Request

**Requestor**  
Matti Kortelainen

**Describe the configuration**  
* Release: CMSSW_12_2_0_pre3
* Run: [346169, 347028]
* GTs:
   * expressGlobalTag: 120X_dataRun3_Express_v2
   * promptrecoGlobalTag: 120X_dataRun3_Prompt_v2
   * alcap0GlobalTag: 120X_dataRun3_Prompt_v2
* Additional changes:

**Purpose of the test**  
Test [Fast cloning merge jobs](https://github.com/cms-sw/cmssw/pull/36026) and [Use noRunLumiSort](https://github.com/cms-sw/cmssw/pull/36221) to check if [High Memory Usage](https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/2304/1/1/2/1/1/1/1/1/2.html) is solved

**T0 Operations HyperNews thread**  
If necessary, provide a link to the HN thread announcing the test to the relevant groups. 
[Tier0 Operations HN Forum](https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops.html?)

### CODE REVIEW

**Comment by jhonatanamado** [comment]
run replay please

**Comment by tvami** [comment]
I'm not sure that this GT will work. I think 12_2_X might look for for example `VeryForwardIdealGeometryRecord` or other PPS related upgrades in the code. The 12_2_X autoCond GTs are
`122X_dataRun3_Prompt_v1` and `122X_dataRun3_Express_v1`

**Comment by jhonatanamado** [comment]
Thanks for the comments @tvami. 
I will add those changes and wait until the previous automatic replay finished to deploy and test this new configuration

**Comment by jhonatanamado** [comment]
run replay please

**Comment by germanfgv** [comment]
run replay please

**Comment by jhonatanamado** [comment]
run replay please

**Comment by jhonatanamado** [comment]
run replay please

**Comment by tvami** [comment]
Did this finish fine? I see "Replay Tests — This test has failed." but maybe that's just the Jenkins, @jhonatanamado

**Comment by jhonatanamado** [comment]
Hi @tvami, we reported on HNs that this replay failed with the same type of issue https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/2325/1.html

**Comment by tvami** [comment]
Thanks @jhonatanamado , in that thread you said "We will keep you posted in this thread if other jobs have issues.", did other workflows finish fine? 
Anyway, I've contacted the pixel experts about the memory issue, let's see how that's resolved.

**Comment by jhonatanamado** [comment]
Hi @tvami  Yes, with the final configuration, all the other workflows finished without issues

**Comment by jhonatanamado** [comment]
Job using more memory than usual was debugged by the experts and the solution was included in CMSSW_12_2_1

**Pull request closed without merging**
