### PR TITLE
Replay test for 12_4_8

### PR DESCRIPTION
**Pull request by sarafiorendi**
# Replay Request

**Requestor**  
ORM

**Describe the configuration**  
* Release: CMSSW_12_4_8
* Run: [356824](https://cmsoms.cern.ch/cms/runs/report?cms_run=356824), [356948](https://cmsoms.cern.ch/cms/runs/report?cms_run=356948) (same as for the [CMSSW_12_4_7 replay](https://github.com/dmwm/T0/pull/4745))
* GTs:
   * expressGlobalTag: 124X_dataRun3_Express_v5
   * promptrecoGlobalTag: 124X_dataRun3_Prompt_v4
   * alcap0GlobalTag: 124X_dataRun3_Prompt_v4
* Additional changes: None

**Purpose of the test**  
Test the new release that will be used for the ReReco of the first part of 2022 data and for data-taking, for which a few fixes are included.

**T0 Operations cmsTalk thread**  
https://cms-talk.web.cern.ch/t/replay-testing-for-cmssw-12-4-8/14321

### CODE REVIEW

**Comment by germanfgv** [comment]
Thanks Sara. I'll prepare the replay.

**Comment by germanfgv** [comment]
The replay has started. It can be followed here:
https://monit-grafana.cern.ch/d/t_jr45h7k/cms-tier0-replayid-monitoring?orgId=11&var-Bin=5m&var-
ReplayID=220825163730&var-JobType=All&var-WorkflowType=All

**Comment by tvami** [comment]
This finished successfully, can we merge it? I'd like to have another limited replay and then it would be best to do that on the top of this.

**Comment by tvami** [comment]
> can we merge it? I

Although it doesnt change the prod config so maybe this is not the form of the PR to merge, I'll open up another test-only one

**Comment by germanfgv** [comment]
This will be merged with #4750

**Pull request closed without merging**
