### PR TITLE
Replay for Run 3 collisions

### PR DESCRIPTION
**Pull request by francescobrivio**
# Replay Request

**Requestor**  
Francesco Brivio for AlCaDB

**Describe the configuration**  
* Release: CMSSW_12_3_3_patch1
* Run: 346512,349840,350966
* GTs:
   * expressGlobalTag: 123X_dataRun3_Express_Candidate_2022_05_19_09_12_41
   * promptrecoGlobalTag: 123X_dataRun3_Prompt_Candidate_2022_05_19_09_16_57
   * alcap0GlobalTag: 123X_dataRun3_Prompt_Candidate_2022_05_19_09_16_57
* Additional changes:
   * Updates to the AlCaRecoMatrix for Run 3 collisions as detailed in [AlCaRecoMatrix#COLLISIONS_2022 twiki](https://twiki.cern.ch/twiki/bin/view/CMS/AlCaRecoMatrix#COLLISIONS_2022)
      * Added some new producers (all already tested in previous replays)
      * Removed some unused producers
      * Added `AlCaPPS` dataset with no producers (RAW dataset will be the only output)
   * Testing GT candidates for Run 3 collisions

**Purpose of the test**  
This replay is to test the *final* configuration for Run 3 collision data taking.

**T0 Operations cmsTalk thread**  
https://cms-talk.web.cern.ch/t/replay-for-testing-the-run-3-collisions-setup/10676

---------
**EDIT** 
As discussed at the [Joint Ops meeting](https://indico.cern.ch/event/1163552/) ([gDoc here](https://docs.google.com/document/d/1ijqqfALY8BYWqVXUelHuZxl1023sHjQsmpZC6Kzrxw0/edit#)), the repacking step should still use `CMSSW_12_3_3`.

### CODE REVIEW

**Comment by francescobrivio** [comment]
test syntax please

**Comment by francescobrivio** [comment]
test syntax please

**Comment by francescobrivio** [comment]
run replay please

 - new release is ready `/cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_3_3_patch1`

**Comment by francescobrivio** [comment]
test syntax please

**Comment by germanfgv** [comment]
run replay please

**Comment by germanfgv** [comment]
run replay please

**Comment by tvami** [comment]
@francescobrivio my understanding is that the content of this is included in https://github.com/dmwm/T0/pull/4678, so I think this PR can be closed.

**Comment by francescobrivio** [comment]
Changes included in https://github.com/dmwm/T0/pull/4678

**Pull request closed without merging**
