### PR TITLE
Enable prompt for ParkingDoubleElectronLowMass* and Update ReplayConfig

### PR DESCRIPTION
**Pull request by jhonatanamado**
Enable prompt for ParkingDoubleElectronLowMass*

### CODE REVIEW

**Comment by jhonatanamado** [comment]
From https://hlt-config-editor-confdbv3.app.cern.ch/open?cfg=%2Fcdaq%2Ftest%2Ftomei%2FRun2022%2Fcollisions%2Fstormv1p3%2FHLT%2FV26&db=online, I believe we are correct. `ParkingDoubleElectronLowMass[0-5]`

**Comment by jhonatanamado** [comment]
@jeyserma, Jan Could you please doble-check the replay config.

**Review by germanfgv — APPROVED** [review]
It looks fine for me. Some of the changes I don't think are necessary, but also they are not harmful so it's ok. Thank you for re-synching with production config.

**Comment by jeyserma** [comment]
I went through the changes and they look fine to me, nothing to add in particular. It's quite some effort to keep it in sync, so we better find a more suitable solution (that's on me - https://its.cern.ch/jira/projects/CMSTZ/issues/CMSTZ-928)

**Pull request merged**
