### PR TITLE
Basic test of possibility to create a pull request by a random user

### PR DESCRIPTION
**Pull request by dvk-test**
Basic test of possibility to create a pull request by a random user

### CODE REVIEW

**Comment by germanfgv** [comment]
test this please

**Comment by germanfgv** [comment]
@drkovalskyi so it seems it is possible to create the PRs. Sorry, our mistake. We still need to figure out how to allow them to trigger the tests. Jenkins allows us to specify a list of GitHub Users or organizations. We could create a Tier0 organization, so that we have direct control over who belongs and who doesn't

**Comment by dvk-test** [comment]
This is a good point. We need github users, not CERN users. So let's create a Tier0 organization and add people there.

**Comment by dvk-test** [comment]
I guess I have to do it, right?

**Comment by drkovalskyi** [comment]
For now I think we can start with just asking users to make a pull request and we will trigger a replay

**Comment by drkovalskyi** [comment]
@germanfgv why do we have all Unit Tests failing?

**Comment by germanfgv** [comment]
test this please

**Comment by germanfgv** [comment]
I had not updated the credentials used in the containers. That's why they failed.

**Pull request closed without merging**
