### PR TITLE
Replay configuration for run 314473 (ppCollision2018)

### PR DESCRIPTION
**Pull request by germanfgv**

### CODE REVIEW

**Comment by germanfgv** [comment]
retest this please

**Comment by gkfthddk** [comment]
Host name : vocms047.cern.ch
Container ID : 1
Pull request url : https://github.com/dmwm/T0/pull/4533
Current build at jenkins : https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-T0-PR-test-job/178/.
Jira Issue : https://its.cern.ch/jira/browse/CMSTZDEV-599

**Comment by germanfgv** [comment]
retest this

**Comment by germanfgv** [comment]
retest this please

**Comment by gkfthddk** [comment]
Host name : vocms047.cern.ch
Container ID : 1
Pull request url : https://github.com/dmwm/T0/pull/4533
Current build at jenkins : https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-T0-PR-test-job/179/.
Jira Issue : https://its.cern.ch/jira/browse/CMSTZDEV-600

**Comment by germanfgv** [comment]
retest this please

**Pull request closed without merging**
