### PR TITLE
Replay testing CMSSW_13_0_7_TOTEM

### PR DESCRIPTION
**Pull request by anpicci**
# Replay Request

**Requestor**  
Shadow ORM

**Describe the configuration**  
* Release: CMSSW\_13\_0\_7\_TOTEM
* Run: 368805 -  Cosmics 2023 - 9 minutes long - all components IN except for GEM and RPC
* GTs:
   * expressGlobalTag: 130X_dataRun3_Express_v2
   * promptrecoGlobalTag: 130X_dataRun3_Prompt_v3

**Purpose of the test**  
Test dedicated release for special TOTEM run

**T0 Operations cmsTalk thread**  
If necessary, provide a link to the cmsTalk thread announcing the test to the relevant groups. 
[Tier0 Operations cmsTalk Forum](https://cms-talk.web.cern.ch/t/replay-testing-cmssw-13-0-7-totem/2549)

### CODE REVIEW

**Comment by mmusich** [comment]
@vavati FYI

**Comment by mmusich** [comment]
for the record, the replay can be followed [here](https://monit-grafana.cern.ch/d/t_jr45h7k/cms-tier0-replayid-monitoring?orgId=11&refresh=1d&var-Bin=30m&var-ReplayID=230615103815&var-JobType=All&var-WorkflowType=All&from=now-24h&to=now).

**Comment by grzanka** [comment]
Is the replay over ? Were there any problems during execution ? Grafana dashboard displays all the jobs completed.

**Comment by mmusich** [comment]
@grzanka 

> Is the replay over ? Were there any problems during execution ? Grafana dashboard displays all the jobs completed.

The replay is over, and no problems were spotted.
It was also announced publicly [here](https://cms-talk.web.cern.ch/t/replay-testing-cmssw-13-0-7-totem/25491/2). I wrote you privately on mattermost, but seems you didn't receive the message.
In any case in the link above you will find the output dataset names.  Please check them and confirm there are no problems.
Thank you.

**Comment by oljemark** [comment]
Hello. Checks on https://cmsweb.cern.ch/das/request?input=dataset%3D%2FMinimumBias%2FTier0_REPLAY_2023-PromptReco-v15103815%2FAOD&instance=prod/global are OK: TOTEM T2 and SiStrips are reconstructed...etc...

**Comment by mmusich** [comment]
@oljemark 

> are OK: TOTEM T2 and SiStrips are reconstructed...etc...

could you please include a link to a presentation and / or plots confirm this is the case?
Thank you.

**Comment by oljemark** [comment]
Hello. I have some DQM plots for T2 here:  
[replay-T2Plots-slide2.pdf](https://github.com/dmwm/T0/files/11770000/replay-T2Plots-slide2.pdf)
[replay-T2Plots-slide1.pdf](https://github.com/dmwm/T0/files/11770001/replay-T2Plots-slide1.pdf)
[replay-T2Plots-slide3.pdf](https://github.com/dmwm/T0/files/11770002/replay-T2Plots-slide3.pdf)
@vavati checked the TrackingStrips plots look reasonable, but here is the DQM file we looked at: 
[DQM_V0001_CTPPS_R000368805.zip](https://github.com/dmwm/T0/files/11770010/DQM_V0001_CTPPS_R000368805.zip)

**Comment by mmusich** [comment]
Thanks @oljemark .
I consider these private checks from the PPD DPG conclusive. @anpicci you might want to close the replay.

**Comment by oljemark** [comment]
We did see TOTEM & CTPPS classes only in the MinBias AOD, not in the cosmics one (https://cmsweb.cern.ch/das/request?input=dataset%3D%2FCosmics%2FTier0_REPLAY_2023-PromptReco-v15103815%2FAOD&instance=prod/global)

**Comment by mmusich** [comment]
> We did see TOTEM & CTPPS classes only in the MinBias AOD, not in the cosmics one 

are you persisting them in the [Cosmics event content](https://github.com/cms-sw/cmssw/blob/master/Configuration/EventContent/python/EventContentCosmics_cff.py)?

**Comment by oljemark** [comment]
No, it seems not; I don't see RecoPPS/Configuration.RecoCTPPS_EventContent_cff.py included there.

**Comment by mmusich** [comment]
> No, it seems not; I don't see RecoPPS/Configuration.RecoCTPPS_EventContent_cff.py included there.

Thanks. So I would conclude it's expected. Please clarify if you would need them in the cosmics PDs as well.

**Comment by oljemark** [comment]
Probably not, but @vavati had suggested I look at MinBias & Cosmics since those two accept triggers based on random.

**Comment by vavati** [comment]
> > No, it seems not; I don't see RecoPPS/Configuration.RecoCTPPS_EventContent_cff.py included there.
> 
> Thanks. So I would conclude it's expected. Please clarify if you would need them in the cosmics PDs as well.

No in general we don't need cosmics. So most likely we are not IN. For the next test in global we should have the dedicated menu so we will have a random PD where for sure we will be IN.

**Pull request closed without merging**
